#!/usr/bin/env python3
"""Generate HanziPlus sectioned vocabulary JSON files."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "HanziPlus" / "Resources" / "Data"
TRAVEL_PATH = DATA_DIR / "travel.json"

# (hanzi, pinyin, english, (ex_h, ex_p, ex_e), (ex_h, ex_p, ex_e))
WordTuple = tuple[str, str, str, tuple[str, str, str], tuple[str, str, str]]


def w(section: str, hanzi: str, pinyin: str, english: str,
      ex1: tuple[str, str, str], ex2: tuple[str, str, str]) -> dict:
    """Build one vocabulary entry with two example sentences."""
    def example(h: str, p: str, e: str) -> dict:
        return {"hanzi": h, "pinyin": p, "english": e}

    return {
        "section": section,
        "hanzi": hanzi,
        "pinyin": pinyin,
        "english": english,
        "examples": [example(*ex1), example(*ex2)],
    }


def section_words(section: str, words: list[WordTuple]) -> list[dict]:
    return [w(section, *word) for word in words]


def load_existing_travel() -> dict[str, dict]:
    if not TRAVEL_PATH.exists():
        return {}
    with TRAVEL_PATH.open(encoding="utf-8") as f:
        items = json.load(f)
    return {item["hanzi"]: item for item in items}


def travel_remap() -> dict[str, str]:
    """Move existing travel words into the new 10-section layout."""
    return {
        "手机": "mobile",
        "无线网": "mobile",
        "钱": "money",
        "现金": "money",
        "刷卡": "money",
        "付款": "money",
        "目的地": "sightseeing",
        "左边": "sightseeing",
        "右边": "sightseeing",
        "直走": "sightseeing",
    }


def build_travel(existing: dict[str, dict]) -> list[dict]:
    remap = travel_remap()
    preserved: dict[str, list[dict]] = {s: [] for s in TRAVEL_SECTIONS}

    for hanzi, item in existing.items():
        section = remap.get(hanzi, item.get("section", "essentials"))
        if section not in preserved:
            continue
        entry = {
            "section": section,
            "hanzi": item["hanzi"],
            "pinyin": item["pinyin"],
            "english": item["english"],
            "examples": item.get("examples", [])[:2],
        }
        if len(entry["examples"]) == 2:
            preserved[section].append(entry)

    supplemental = {
        "essentials": section_words("essentials", [
            ("护照", "hùzhào", "passport",
             ("请出示您的护照。", "Qǐng chūshì nín de hùzhào.", "Please show your passport."),
             ("我的护照在包里。", "Wǒ de hùzhào zài bāo lǐ.", "My passport is in my bag.")),
            ("签证", "qiānzhèng", "visa",
             ("我需要办理签证吗？", "Wǒ xūyào bànlǐ qiānzhèng ma?", "Do I need to apply for a visa?"),
             ("他的签证还有一个月到期。", "Tā de qiānzhèng hái yǒu yī gè yuè dàoqī.", "His visa expires in one month.")),
        ]),
        "airport": section_words("airport", [
            ("转机", "zhuǎnjī", "to transfer flights",
             ("我需要在上海转机。", "Wǒ xūyào zài Shànghǎi zhuǎnjī.", "I need to transfer in Shanghai."),
             ("转机时间只有一小时。", "Zhuǎnjī shíjiān zhǐyǒu yī xiǎoshí.", "The layover is only one hour.")),
            ("托运", "tuōyùn", "to check luggage",
             ("这个箱子需要托运吗？", "Zhège xiāngzi xūyào tuōyùn ma?", "Does this suitcase need to be checked?"),
             ("我已经办好托运了。", "Wǒ yǐjīng bànhǎo tuōyùn le.", "I've already checked my luggage.")),
        ]),
        "hotel": section_words("hotel", [
            ("单人间", "dānrénjiān", "single room",
             ("请问还有单人间吗？", "Qǐngwèn hái yǒu dānrénjiān ma?", "Do you still have single rooms?"),
             ("我预订了一间单人间。", "Wǒ yùdìng le yī jiān dānrénjiān.", "I booked a single room.")),
            ("押金", "yājīn", "deposit",
             ("入住需要交押金吗？", "Rùzhù xūyào jiāo yājīn ma?", "Do I need to pay a deposit at check-in?"),
             ("退房后押金会退还。", "Tuìfáng hòu yājīn huì tuìhuán.", "The deposit will be refunded after checkout.")),
        ]),
        "transportation": section_words("transportation", [
            ("站台", "zhàntái", "platform",
             ("请问三号站台在哪儿？", "Qǐngwèn sān hào zhàntái zài nǎr?", "Where is platform three?"),
             ("火车已经到站台了。", "Huǒchē yǐjīng dào zhàntái le.", "The train has arrived at the platform.")),
            ("换乘", "huànchéng", "to transfer (transit)",
             ("下一站可以换乘二号线。", "Xià yī zhàn kěyǐ huànchéng èr hào xiàn.", "You can transfer to Line 2 at the next stop."),
             ("我在人民广场换乘。", "Wǒ zài Rénmín Guǎngchǎng huànchéng.", "I transfer at People's Square.")),
        ]),
        "restaurant": section_words("restaurant", [
            ("打包", "dǎbāo", "to take away / to-go",
             ("请帮我打包。", "Qǐng bāng wǒ dǎbāo.", "Please pack this to go."),
             ("剩下的可以打包吗？", "Shèngxià de kěyǐ dǎbāo ma?", "Can I take the leftovers to go?"),
             ),
            ("过敏", "guòmǐn", "allergy",
             ("我对花生过敏。", "Wǒ duì huāshēng guòmǐn.", "I'm allergic to peanuts."),
             ("请问这道菜有过敏原吗？", "Qǐngwèn zhè dào cài yǒu guòmǐnyuán ma?", "Does this dish contain allergens?")),
        ]),
        "shopping": section_words("shopping", [
            ("免税", "miǎnshuì", "tax-free",
             ("这个商店可以免税吗？", "Zhège shāngdiàn kěyǐ miǎnshuì ma?", "Is this store tax-free?"),
             ("我在机场买了免税商品。", "Wǒ zài jīchǎng mǎi le miǎnshuì shāngpǐn.", "I bought duty-free items at the airport.")),
            ("退税", "tuìshuì", "tax refund",
             ("游客可以在机场办理退税。", "Yóukè kěyǐ zài jīchǎng bànlǐ tuìshuì.", "Tourists can get a tax refund at the airport."),
             ("请保留发票以便退税。", "Qǐng bǎoliú fāpiào yǐbiàn tuìshuì.", "Please keep the receipt for a tax refund.")),
        ]),
        "sightseeing": section_words("sightseeing", [
            ("景点", "jǐngdiǎn", "scenic spot / attraction",
             ("这个景点很有名。", "Zhège jǐngdiǎn hěn yǒumíng.", "This attraction is very famous."),
             ("我们今天去三个景点。", "Wǒmen jīntiān qù sān gè jǐngdiǎn.", "We're visiting three sights today.")),
            ("门票", "ménpiào", "admission ticket",
             ("门票多少钱一张？", "Ménpiào duōshao qián yī zhāng?", "How much is one admission ticket?"),
             ("学生可以买优惠门票。", "Xuésheng kěyǐ mǎi yōuhuì ménpiào.", "Students can buy discounted tickets.")),
            ("导游", "dǎoyóu", "tour guide",
             ("导游用中文讲解。", "Dǎoyóu yòng Zhōngwén jiǎngjiě.", "The guide explains in Chinese."),
             ("我们需要一位英文导游。", "Wǒmen xūyào yī wèi Yīngwén dǎoyóu.", "We need an English-speaking guide.")),
            ("拍照", "pāizhào", "to take photos",
             ("这里可以拍照吗？", "Zhèlǐ kěyǐ pāizhào ma?", "Can I take photos here?"),
             ("请帮我拍张照片。", "Qǐng bāng wǒ pāi zhāng zhàopiàn.", "Please take a photo for me.")),
            ("博物馆", "bówùguǎn", "museum",
             ("博物馆周一闭馆。", "Bówùguǎn zhōuyī bìguǎn.", "The museum is closed on Mondays."),
             ("我们在博物馆待了两个小时。", "Wǒmen zài bówùguǎn dāi le liǎng gè xiǎoshí.", "We spent two hours at the museum.")),
            ("故宫", "Gùgōng", "Forbidden City",
             ("故宫是北京必去的景点。", "Gùgōng shì Běijīng bì qù de jǐngdiǎn.", "The Forbidden City is a must-see in Beijing."),
             ("我们早上参观了故宫。", "Wǒmen zǎoshang cānguān le Gùgōng.", "We visited the Forbidden City this morning.")),
        ]),
        "mobile": section_words("mobile", [
            ("流量", "liúliàng", "mobile data",
             ("我的流量用完了。", "Wǒ de liúliàng yòng wán le.", "I've used up my mobile data."),
             ("这里有免费的流量吗？", "Zhèlǐ yǒu miǎnfèi de liúliàng ma?", "Is there free mobile data here?")),
            ("充电", "chōngdiàn", "to charge (a device)",
             ("请问哪里可以充电？", "Qǐngwèn nǎlǐ kěyǐ chōngdiàn?", "Where can I charge my phone?"),
             ("我的手机需要充电。", "Wǒ de shǒujī xūyào chōngdiàn.", "My phone needs charging.")),
            ("扫码", "sǎomǎ", "to scan a QR code",
             ("请扫码支付。", "Qǐng sǎomǎ zhīfù.", "Please pay by scanning the QR code."),
             ("进站要先扫码。", "Jìn zhàn yào xiān sǎomǎ.", "You need to scan a code before entering.")),
            ("密码", "mìmǎ", "password",
             ("无线网的密码是什么？", "Wúxiànwǎng de mìmǎ shì shénme?", "What's the Wi-Fi password?"),
             ("请输入您的密码。", "Qǐng shūrù nín de mìmǎ.", "Please enter your password.")),
            ("网络", "wǎngluò", "network / internet",
             ("这里的网络很快。", "Zhèlǐ de wǎngluò hěn kuài.", "The network here is fast."),
             ("我的网络连接不上。", "Wǒ de wǎngluò liánjiē bù shàng.", "I can't connect to the network.")),
            ("微信", "Wēixìn", "WeChat",
             ("我们可以加微信吗？", "Wǒmen kěyǐ jiā Wēixìn ma?", "Can we add each other on WeChat?"),
             ("请用微信发给我地址。", "Qǐng yòng Wēixìn fā gěi wǒ dìzhǐ.", "Please send me the address on WeChat.")),
            ("SIM卡", "SIM kǎ", "SIM card",
             ("请帮我换一张SIM卡。", "Qǐng bāng wǒ huàn yī zhāng SIM kǎ.", "Please help me replace the SIM card."),
             ("机场可以买到旅游SIM卡。", "Jīchǎng kěyǐ mǎi dào lǚyóu SIM kǎ.", "You can buy a travel SIM card at the airport.")),
            ("漫游", "mànyóu", "roaming",
             ("出国前请开通国际漫游。", "Chūguó qián qǐng kāitōng guójì mànyóu.", "Enable international roaming before going abroad."),
             ("漫游费用比较高。", "Mànyóu fèiyòng bǐjiào gāo.", "Roaming charges are relatively high.")),
        ]),
        "money": section_words("money", [
            ("支付宝", "Zhīfùbǎo", "Alipay",
             ("这里可以用支付宝吗？", "Zhèlǐ kěyǐ yòng Zhīfùbǎo ma?", "Can I pay with Alipay here?"),
             ("我习惯用支付宝付款。", "Wǒ xíguàn yòng Zhīfùbǎo fùkuǎn.", "I usually pay with Alipay.")),
            ("微信支付", "Wēixìn zhīfù", "WeChat Pay",
             ("请打开微信支付。", "Qǐng dǎkāi Wēixìn zhīfù.", "Please open WeChat Pay."),
             ("小店只接受微信支付。", "Xiǎodiàn zhǐ jiēshòu Wēixìn zhīfù.", "The shop only accepts WeChat Pay.")),
            ("汇率", "huìlǜ", "exchange rate",
             ("今天的汇率是多少？", "Jīntiān de huìlǜ shì duōshao?", "What's the exchange rate today?"),
             ("汇率每天都在变化。", "Huìlǜ měitiān dōu zài biànhuà.", "The exchange rate changes every day.")),
            ("找零", "zhǎolíng", "change (money returned)",
             ("请不用找零了。", "Qǐng búyòng zhǎolíng le.", "Keep the change, please."),
             ("店员找零很及时。", "Diànyuán zhǎolíng hěn jíshí.", "The clerk gave change promptly.")),
            ("收据", "shōujù", "receipt",
             ("请给我一张收据。", "Qǐng gěi wǒ yī zhāng shōujù.", "Please give me a receipt."),
             ("收据我放钱包里了。", "Shōujù wǒ fàng qiánbāo lǐ le.", "I put the receipt in my wallet.")),
            ("预算", "yùsuàn", "budget",
             ("我的旅行预算有限。", "Wǒ de lǚxíng yùsuàn yǒuxiàn.", "My travel budget is limited."),
             ("我们按预算安排行程。", "Wǒmen àn yùsuàn ānpái xíngchéng.", "We plan the trip according to our budget.")),
        ]),
        "emergency": section_words("emergency", [
            ("丢失", "diūshī", "to lose",
             ("我的钱包丢了。", "Wǒ de qiánbāo diū le.", "I lost my wallet."),
             ("请在服务台报失。", "Qǐng zài fúwùtái bàoshī.", "Please report the loss at the service desk.")),
        ]),
    }

    result: dict[str, list[dict]] = {s: [] for s in TRAVEL_SECTIONS}
    seen: dict[str, set[str]] = {s: set() for s in TRAVEL_SECTIONS}

    for section in TRAVEL_SECTIONS:
        for item in preserved[section] + supplemental.get(section, []):
            if item["hanzi"] in seen[section]:
                continue
            if len(result[section]) >= 10:
                break
            seen[section].add(item["hanzi"])
            item["section"] = section
            result[section].append(item)

    output: list[dict] = []
    for section in TRAVEL_SECTIONS:
        words = result[section]
        if len(words) < 10:
            raise ValueError(f"travel.{section} has only {len(words)} words")
        output.extend(words[:10])
    return output


TRAVEL_SECTIONS = [
    "essentials", "airport", "hotel", "transportation", "restaurant",
    "shopping", "sightseeing", "mobile", "money", "emergency",
]


def build_business() -> list[dict]:
    data = {
        "meetings": [
            ("会议", "huìyì", "meeting",
             ("下午三点有个会议。", "Xiàwǔ sān diǎn yǒu gè huìyì.", "There's a meeting at 3 p.m."),
             ("会议改到明天了。", "Huìyì gǎi dào míngtiān le.", "The meeting has been moved to tomorrow.")),
            ("议程", "yìchéng", "agenda",
             ("请看一下今天的议程。", "Qǐng kàn yīxià jīntiān de yìchéng.", "Please review today's agenda."),
             ("议程已经发给大家了。", "Yìchéng yǐjīng fā gěi dàjiā le.", "The agenda has been sent to everyone.")),
            ("汇报", "huìbào", "to report / briefing",
             ("请各部门汇报进度。", "Qǐng gè bùmén huìbào jìndù.", "Please have each department report progress."),
             ("他刚做完项目汇报。", "Tā gāng zuò wán xiàngmù huìbào.", "He just finished the project briefing.")),
            ("讨论", "tǎolùn", "to discuss",
             ("我们先讨论这个问题。", "Wǒmen xiān tǎolùn zhège wèntí.", "Let's discuss this issue first."),
             ("会上讨论得很热烈。", "Huì shàng tǎolùn de hěn rèliè.", "The discussion in the meeting was lively.")),
            ("总结", "zǒngjié", "to summarize",
             ("请帮我总结一下要点。", "Qǐng bāng wǒ zǒngjié yīxià yàodiǎn.", "Please summarize the key points for me."),
             ("会议最后做了总结。", "Huìyì zuìhòu zuò le zǒngjié.", "We summarized at the end of the meeting.")),
            ("准时", "zhǔnshí", "on time / punctual",
             ("请大家准时参加会议。", "Qǐng dàjiā zhǔnshí cānjiā huìyì.", "Please attend the meeting on time."),
             ("他一向很准时。", "Tā yīxiàng hěn zhǔnshí.", "He is always punctual.")),
            ("延期", "yánqī", "to postpone",
             ("项目可能会延期。", "Xiàngmù kěnéng huì yánqī.", "The project may be postponed."),
             ("会议延期到下周。", "Huìyì yánqī dào xià zhōu.", "The meeting is postponed to next week.")),
            ("记录", "jìlù", "to record / minutes",
             ("请做好会议记录。", "Qǐng zuò hǎo huìyì jìlù.", "Please take good meeting minutes."),
             ("我把要点都记录下来了。", "Wǒ bǎ yàodiǎn dōu jìlù xiàlái le.", "I wrote down all the key points.")),
            ("参会", "cānhuì", "to attend a meeting",
             ("你需要参会吗？", "Nǐ xūyào cānhuì ma?", "Do you need to attend the meeting?"),
             ("所有主管都要参会。", "Suǒyǒu zhǔguǎn dōu yào cānhuì.", "All managers must attend.")),
            ("决议", "juéyì", "resolution / decision",
             ("会议通过了这项决议。", "Huìyì tōngguò le zhè xiàng juéyì.", "The meeting passed this resolution."),
             ("请执行会议决议。", "Qǐng zhíxíng huìyì juéyì.", "Please implement the meeting decision.")),
        ],
        "email": [
            ("邮件", "yóujiàn", "email",
             ("我收到你的邮件了。", "Wǒ shōudào nǐ de yóujiàn le.", "I received your email."),
             ("请查收附件邮件。", "Qǐng cháshōu fùjiàn yóujiàn.", "Please check the attached email.")),
            ("附件", "fùjiàn", "attachment",
             ("报告在邮件附件里。", "Bàogào zài yóujiàn fùjiàn lǐ.", "The report is in the email attachment."),
             ("请加上合同附件。", "Qǐng jiā shàng hétong fùjiàn.", "Please add the contract as an attachment.")),
            ("回复", "huífù", "to reply",
             ("请尽快回复这封邮件。", "Qǐng jǐnkuài huífù zhè fēng yóujiàn.", "Please reply to this email soon."),
             ("我已经回复客户了。", "Wǒ yǐjīng huífù kèhù le.", "I've already replied to the client.")),
            ("抄送", "chāosòng", "to CC (carbon copy)",
             ("请抄送给财务部门。", "Qǐng chāosòng gěi cáiwù bùmén.", "Please CC the finance department."),
             ("我把经理抄送在邮件里。", "Wǒ bǎ jīnglǐ chāosòng zài yóujiàn lǐ.", "I CC'd the manager on the email.")),
            ("主题", "zhǔtí", "subject (line)",
             ("请修改邮件主题。", "Qǐng xiūgǎi yóujiàn zhǔtí.", "Please change the email subject."),
             ("邮件主题要写清楚。", "Yóujiàn zhǔtí yào xiě qīngchu.", "The email subject should be clear.")),
            ("转发", "zhuǎnfā", "to forward",
             ("我把邮件转发给你了。", "Wǒ bǎ yóujiàn zhuǎnfā gěi nǐ le.", "I forwarded the email to you."),
             ("请转发给相关同事。", "Qǐng zhuǎnfā gěi xiāngguān tóngshì.", "Please forward it to relevant colleagues.")),
            ("确认", "quèrèn", "to confirm",
             ("请确认收到这封邮件。", "Qǐng quèrèn shōudào zhè fēng yóujiàn.", "Please confirm receipt of this email."),
             ("客户已确认订单。", "Kèhù yǐ quèrèn dìngdān.", "The client has confirmed the order.")),
            ("通知", "tōngzhī", "to notify / notice",
             ("公司已发出正式通知。", "Gōngsī yǐ fāchū zhèngshì tōngzhī.", "The company has issued an official notice."),
             ("请通知所有员工。", "Qǐng tōngzhī suǒyǒu yuángōng.", "Please notify all employees.")),
            ("沟通", "gōutōng", "to communicate",
             ("我们需要加强沟通。", "Wǒmen xūyào jiāqiáng gōutōng.", "We need to improve communication."),
             ("邮件沟通效率很高。", "Yóujiàn gōutōng xiàolǜ hěn gāo.", "Email communication is very efficient.")),
            ("收件人", "shōujiànrén", "recipient",
             ("请检查收件人地址。", "Qǐng jiǎnchá shōujiànrén dìzhǐ.", "Please check the recipient address."),
             ("收件人填错了。", "Shōujiànrén tián cuò le.", "The recipient was entered incorrectly.")),
        ],
        "sales": [
            ("客户", "kèhù", "client / customer",
             ("这个客户很重要。", "Zhège kèhù hěn zhòngyào.", "This client is very important."),
             ("请跟进新客户。", "Qǐng gēnjìn xīn kèhù.", "Please follow up with the new client.")),
            ("订单", "dìngdān", "order",
             ("客户下了大订单。", "Kèhù xià le dà dìngdān.", "The client placed a large order."),
             ("订单已经确认了。", "Dìngdān yǐjīng quèrèn le.", "The order has been confirmed.")),
            ("报价", "bàojià", "price quote",
             ("请发一份报价单。", "Qǐng fā yī fèn bàojià dān.", "Please send a price quote."),
             ("他们的报价比我们低。", "Tāmen de bàojià bǐ wǒmen dī.", "Their quote is lower than ours.")),
            ("促销", "cùxiāo", "promotion / sale",
             ("商场正在做促销。", "Shāngchǎng zhèngzài zuò cùxiāo.", "The mall is running a promotion."),
             ("促销活动很成功。", "Cùxiāo huódòng hěn chénggōng.", "The promotion was very successful.")),
            ("市场", "shìchǎng", "market",
             ("中国市场增长很快。", "Zhōngguó shìchǎng zēngzhǎng hěn kuài.", "The Chinese market is growing fast."),
             ("我们要开拓新市场。", "Wǒmen yào kāituò xīn shìchǎng.", "We want to expand into new markets.")),
            ("目标", "mùbiāo", "target / goal",
             ("本季度销售目标很高。", "Běn jìdù xiāoshòu mùbiāo hěn gāo.", "This quarter's sales target is high."),
             ("我们已经完成目标了。", "Wǒmen yǐjīng wánchéng mùbiāo le.", "We've already met the target.")),
            ("推广", "tuīguǎng", "to promote / marketing",
             ("新产品需要推广。", "Xīn chǎnpǐn xūyào tuīguǎng.", "The new product needs marketing."),
             ("他们在网上做推广。", "Tāmen zài wǎngshàng zuò tuīguǎng.", "They're doing online promotion.")),
            ("需求", "xūqiú", "demand / need",
             ("市场需求在增加。", "Shìchǎng xūqiú zài zēngjiā.", "Market demand is increasing."),
             ("请先了解客户需求。", "Qǐng xiān liǎojiě kèhù xūqiú.", "Please understand the client's needs first.")),
            ("业绩", "yèjì", "performance / sales results",
             ("他的业绩很好。", "Tā de yèjì hěn hǎo.", "His sales performance is excellent."),
             ("公司业绩稳步提升。", "Gōngsī yèjì wěnbù tíshēng.", "Company performance is steadily improving.")),
            ("签约", "qiānyuē", "to sign a contract",
             ("客户同意签约了。", "Kèhù tóngyì qiānyuē le.", "The client agreed to sign."),
             ("我们下周签约。", "Wǒmen xià zhōu qiānyuē.", "We're signing next week.")),
        ],
        "manufacturing": [
            ("生产", "shēngchǎn", "production / to produce",
             ("工厂正在满负荷生产。", "Gōngchǎng zhèngzài mǎn fùhè shēngchǎn.", "The factory is producing at full capacity."),
             ("这条线每天生产一千件。", "Zhè tiáo xiàn měitiān shēngchǎn yī qiān jiàn.", "This line produces a thousand units daily.")),
            ("质量", "zhìliàng", "quality",
             ("产品质量必须达标。", "Chǎnpǐn zhìliàng bìxū dábiāo.", "Product quality must meet standards."),
             ("我们在提高质量。", "Wǒmen zài tígāo zhìliàng.", "We're improving quality.")),
            ("车间", "chējiān", "workshop / shop floor",
             ("请去车间看一下。", "Qǐng qù chējiān kàn yīxià.", "Please go check the workshop."),
             ("车间工人很认真。", "Chējiān gōngrén hěn rènzhēn.", "The shop floor workers are diligent.")),
            ("原料", "yuánliào", "raw materials",
             ("原料价格上涨了。", "Yuánliào jiàgé shàngzhǎng le.", "Raw material prices have gone up."),
             ("仓库里原料充足。", "Cāngkù lǐ yuánliào chōngzú.", "We have sufficient raw materials in storage.")),
            ("设备", "shèbèi", "equipment",
             ("设备需要定期维护。", "Shèbèi xūyào dìngqī wéihù.", "Equipment needs regular maintenance."),
             ("新设备已经安装好了。", "Xīn shèbèi yǐjīng ānzhuāng hǎo le.", "The new equipment has been installed.")),
            ("装配", "zhuāngpèi", "assembly / to assemble",
             ("装配工序很严格。", "Zhuāngpèi gōngxù hěn yángé.", "The assembly process is very strict."),
             ("工人正在装配零件。", "Gōngrén zhèngzài zhuāngpèi língjiàn.", "Workers are assembling parts.")),
            ("检测", "jiǎncè", "inspection / testing",
             ("每批产品都要检测。", "Měi pī chǎnpǐn dōu yào jiǎncè.", "Every batch must be tested."),
             ("检测结果显示合格。", "Jiǎncè jiéguǒ xiǎnshì hégé.", "Test results show it's qualified.")),
            ("产量", "chǎnliàng", "output / production volume",
             ("本月产量创纪录了。", "Běn yuè chǎnliàng chuàng jìlù le.", "This month's output set a record."),
             ("我们要提高产量。", "Wǒmen yào tígāo chǎnliàng.", "We need to increase output.")),
            ("流水线", "liúshuǐxiàn", "assembly line",
             ("流水线运行很稳定。", "Liúshuǐxiàn yùnxíng hěn wěndìng.", "The assembly line runs smoothly."),
             ("新流水线已经投产。", "Xīn liúshuǐxiàn yǐjīng tóuchǎn.", "The new line is now in production.")),
            ("标准", "biāozhǔn", "standard",
             ("产品必须符合国家标准。", "Chǎnpǐn bìxū fúhé guójiā biāozhǔn.", "Products must meet national standards."),
             ("我们提高了生产标准。", "Wǒmen tígāo le shēngchǎn biāozhǔn.", "We raised our production standards.")),
        ],
        "logistics": [
            ("发货", "fāhuò", "to ship / dispatch",
             ("订单今天可以发货。", "Dìngdān jīntiān kěyǐ fāhuò.", "The order can ship today."),
             ("仓库已经安排发货了。", "Cāngkù yǐjīng ānpái fāhuò le.", "The warehouse has arranged shipment.")),
            ("物流", "wùliú", "logistics",
             ("物流信息已更新。", "Wùliú xìnxī yǐ gēngxīn.", "Logistics info has been updated."),
             ("我们换了新的物流公司。", "Wǒmen huàn le xīn de wùliú gōngsī.", "We switched to a new logistics company.")),
            ("仓库", "cāngkù", "warehouse",
             ("货物在仓库里。", "Huòwù zài cāngkù lǐ.", "The goods are in the warehouse."),
             ("仓库管理很规范。", "Cāngkù guǎnlǐ hěn guīfàn.", "Warehouse management is well organized.")),
            ("运输", "yùnshū", "transport / shipping",
             ("运输时间大约三天。", "Yùnshū shíjiān dàyuē sān tiān.", "Shipping takes about three days."),
             ("这批货走海运运输。", "Zhè pī huò zǒu hǎiyùn yùnshū.", "This batch goes by sea freight.")),
            ("报关", "bàoguān", "customs declaration",
             ("出口货物需要报关。", "Chūkǒu huòwù xūyào bàoguān.", "Export goods require customs clearance."),
             ("报关手续已经办好了。", "Bàoguān shǒuxù yǐjīng bànhǎo le.", "Customs procedures are complete.")),
            ("快递", "kuàidì", "express delivery",
             ("请用快递寄样品。", "Qǐng yòng kuàidì jì yàngpǐn.", "Please send the sample by express."),
             ("快递明天能到。", "Kuàidì míngtiān néng dào.", "The express package arrives tomorrow.")),
            ("包装", "bāozhuāng", "packaging",
             ("请加强产品包装。", "Qǐng jiāqiáng chǎnpǐn bāozhuāng.", "Please strengthen the product packaging."),
             ("包装不能破损。", "Bāozhuāng bùnéng pòsǔn.", "Packaging must not be damaged.")),
            ("签收", "qiānshōu", "to sign for delivery",
             ("请在快递单上签收。", "Qǐng zài kuàidì dān shàng qiānshōu.", "Please sign on the delivery slip."),
             ("客户已经签收了。", "Kèhù yǐjīng qiānshōu le.", "The client has signed for it.")),
            ("延误", "yánwù", "delay",
             ("航班延误影响了发货。", "Hángbān yánwù yǐngxiǎng le fāhuò.", "Flight delays affected shipping."),
             ("请说明延误原因。", "Qǐng shuōmíng yánwù yuányīn.", "Please explain the reason for the delay.")),
            ("跟踪", "gēnzōng", "to track",
             ("你可以在线跟踪包裹。", "Nǐ kěyǐ zàixiàn gēnzōng bāoguǒ.", "You can track the package online."),
             ("物流部门在跟踪货物。", "Wùliú bùmén zài gēnzōng huòwù.", "Logistics is tracking the shipment.")),
        ],
        "finance": [
            ("发票", "fāpiào", "invoice / receipt (tax)",
             ("请开具增值税发票。", "Qǐng kāijù zēngzhíshuì fāpiào.", "Please issue a VAT invoice."),
             ("发票已经寄给客户了。", "Fāpiào yǐjīng jì gěi kèhù le.", "The invoice has been sent to the client.")),
            ("付款", "fùkuǎn", "payment",
             ("请在月底前付款。", "Qǐng zài yuè dǐ qián fùkuǎn.", "Please pay before month end."),
             ("客户已经付款了。", "Kèhù yǐjīng fùkuǎn le.", "The client has already paid.")),
            ("预算", "yùsuàn", "budget",
             ("本季度预算很紧张。", "Běn jìdù yùsuàn hěn jǐnzhāng.", "This quarter's budget is tight."),
             ("请提交部门预算。", "Qǐng tíjiāo bùmén yùsuàn.", "Please submit the department budget.")),
            ("成本", "chéngběn", "cost",
             ("我们要控制成本。", "Wǒmen yào kòngzhì chéngběn.", "We need to control costs."),
             ("原材料成本上升了。", "Yuáncáiliào chéngběn shàngshēng le.", "Raw material costs have risen.")),
            ("利润", "lìrùn", "profit",
             ("公司利润稳步增长。", "Gōngsī lìrùn wěnbù zēngzhǎng.", "Company profits are growing steadily."),
             ("这笔订单利润不错。", "Zhè bǐ dìngdān lìrùn búcuò.", "This order has good profit margins.")),
            ("账户", "zhànghù", "account",
             ("请把款打到这个账户。", "Qǐng bǎ kuǎn dǎ dào zhège zhànghù.", "Please transfer payment to this account."),
             ("公司账户余额充足。", "Gōngsī zhànghù yú'é chōngzú.", "The company account has sufficient funds.")),
            ("转账", "zhuǎnzhàng", "bank transfer",
             ("请通过银行转账。", "Qǐng tōngguò yínháng zhuǎnzhàng.", "Please pay by bank transfer."),
             ("我已经转账了。", "Wǒ yǐjīng zhuǎnzhàng le.", "I've already transferred the money.")),
            ("报销", "bàoxiāo", "expense reimbursement",
             ("出差费用可以报销。", "Chūchāi fèiyòng kěyǐ bàoxiāo.", "Business trip expenses can be reimbursed."),
             ("请提交报销单据。", "Qǐng tíjiāo bàoxiāo dānjù.", "Please submit reimbursement receipts.")),
            ("审计", "shěnjì", "audit",
             ("公司正在进行审计。", "Gōngsī zhèngzài jìnxíng shěnjì.", "The company is undergoing an audit."),
             ("审计报告下月出来。", "Shěnjì bàogào xià yuè chūlái.", "The audit report comes out next month.")),
            ("汇率", "huìlǜ", "exchange rate",
             ("汇率波动影响了利润。", "Huìlǜ bōdòng yǐngxiǎng le lìrùn.", "Exchange rate fluctuations affected profits."),
             ("请查一下今天的汇率。", "Qǐng chá yīxià jīntiān de huìlǜ.", "Please check today's exchange rate.")),
        ],
        "phone": [
            ("来电", "láidiàn", "incoming call",
             ("您有一个来电。", "Nín yǒu yī gè láidiàn.", "You have an incoming call."),
             ("刚才有个重要来电。", "Gāngcái yǒu gè zhòngyào láidiàn.", "There was an important call just now.")),
            ("回电", "huídiàn", "to call back",
             ("我会稍后回电。", "Wǒ huì shāohòu huídiàn.", "I'll call you back later."),
             ("请尽快回电。", "Qǐng jǐnkuài huídiàn.", "Please call back as soon as possible.")),
            ("留言", "liúyán", "to leave a message",
             ("他不在，请留言。", "Tā bú zài, qǐng liúyán.", "He's not here, please leave a message."),
             ("我在语音信箱留了言。", "Wǒ zài yǔyīn xìnxiāng liú le yán.", "I left a message on voicemail.")),
            ("接通", "jiētōng", "to connect (a call)",
             ("电话一直接不通。", "Diànhuà yīzhí jiē bù tōng.", "The call won't connect."),
             ("终于接通了。", "Zhōngyú jiētōng le.", "We finally got through.")),
            ("占线", "zhànxiàn", "busy (phone line)",
             ("他的电话占线。", "Tā de diànhuà zhànxiàn.", "His line is busy."),
             ("请稍后再拨，线路占线。", "Qǐng shāohòu zài bō, xiànlù zhànxiàn.", "Please try again later, the line is busy.")),
            ("会议电话", "huìyì diànhuà", "conference call",
             ("十点有会议电话。", "Shí diǎn yǒu huìyì diànhuà.", "There's a conference call at ten."),
             ("请接入会议电话。", "Qǐng jiērù huìyì diànhuà.", "Please join the conference call.")),
            ("信号", "xìnhào", "signal",
             ("这里信号不好。", "Zhèlǐ xìnhào bù hǎo.", "The signal is poor here."),
             ("我听不到，信号太差。", "Wǒ tīng bú dào, xìnhào tài chà.", "I can't hear you, the signal is too weak.")),
            ("挂断", "guàduàn", "to hang up",
             ("请先别挂断。", "Qǐng xiān bié guàduàn.", "Please don't hang up yet."),
             ("他说完就挂断了。", "Tā shuō wán jiù guàduàn le.", "He hung up after speaking.")),
            ("拨打", "bōdǎ", "to dial",
             ("请拨打客服热线。", "Qǐng bōdǎ kèfú rèxiàn.", "Please dial the customer service hotline."),
             ("我拨打了三次都没人接。", "Wǒ bōdǎ le sān cì dōu méi rén jiē.", "I dialed three times with no answer.")),
            ("通话", "tōnghuà", "phone call / conversation",
             ("我们的通话被录音。", "Wǒmen de tōnghuà bèi lùyīn.", "Our call is being recorded."),
             ("通话时间不要太长。", "Tōnghuà shíjiān bú yào tài cháng.", "Don't make the call too long.")),
        ],
        "office": [
            ("同事", "tóngshì", "colleague",
             ("我的同事很帮忙。", "Wǒ de tóngshì hěn bāngmáng.", "My colleagues are very helpful."),
             ("请把这个交给同事。", "Qǐng bǎ zhège jiāo gěi tóngshì.", "Please give this to a colleague.")),
            ("部门", "bùmén", "department",
             ("他在销售部门工作。", "Tā zài xiāoshòu bùmén gōngzuò.", "He works in the sales department."),
             ("请各部门提交报告。", "Qǐng gè bùmén tíjiāo bàogào.", "Please have each department submit a report.")),
            ("加班", "jiābān", "to work overtime",
             ("今晚可能要加班。", "Jīn wǎn kěnéng yào jiābān.", "We may need to work overtime tonight."),
             ("他最近经常加班。", "Tā zuìjìn jīngcháng jiābān.", "He's been working overtime a lot lately.")),
            ("请假", "qǐngjià", "to request leave",
             ("我想请明天假。", "Wǒ xiǎng qǐng míngtiān jià.", "I'd like to take tomorrow off."),
             ("她请假去医院了。", "Tā qǐngjià qù yīyuàn le.", "She took leave to go to the hospital.")),
            ("打印", "dǎyìn", "to print",
             ("请帮我打印这份文件。", "Qǐng bāng wǒ dǎyìn zhè fèn wénjiàn.", "Please print this document for me."),
             ("打印机没纸了。", "Dǎyìnjī méi zhǐ le.", "The printer is out of paper.")),
            ("复印", "fùyìn", "to photocopy",
             ("请复印五份合同。", "Qǐng fùyìn wǔ fèn hétong.", "Please make five copies of the contract."),
             ("复印机在那边。", "Fùyìnjī zài nàbiān.", "The copier is over there.")),
            ("文件", "wénjiàn", "document / file",
             ("文件已经发给你了。", "Wénjiàn yǐjīng fā gěi nǐ le.", "The document has been sent to you."),
             ("请归档这份文件。", "Qǐng guīdàng zhè fèn wénjiàn.", "Please file this document.")),
            ("日程", "rìchéng", "schedule / agenda",
             ("看一下今天的日程。", "Kàn yīxià jīntiān de rìchéng.", "Check today's schedule."),
             ("我把会议加进日程了。", "Wǒ bǎ huìyì jiā jìn rìchéng le.", "I added the meeting to the schedule.")),
            ("汇报", "huìbào", "to report to superiors",
             ("请向经理汇报情况。", "Qǐng xiàng jīnglǐ huìbào qíngkuàng.", "Please report the situation to the manager."),
             ("他每周一向老板汇报。", "Tā měi zhōuyī xiàng lǎobǎn huìbào.", "He reports to the boss every Monday.")),
            ("办公", "bàngōng", "to work / office work",
             ("我在办公室办公。", "Wǒ zài bàngōngshì bàngōng.", "I work in the office."),
             ("今天在家办公。", "Jīntiān zài jiā bàngōng.", "I'm working from home today.")),
        ],
        "negotiations": [
            ("谈判", "tánpàn", "negotiation",
             ("谈判进行了三个小时。", "Tánpàn jìnxíng le sān gè xiǎoshí.", "The negotiation lasted three hours."),
             ("双方谈判很顺利。", "Shuāngfāng tánpàn hěn shùnlì.", "Both sides negotiated smoothly.")),
            ("条件", "tiáojiàn", "terms / conditions",
             ("请说明合作条件。", "Qǐng shuōmíng hézuò tiáojiàn.", "Please explain the cooperation terms."),
             ("这些条件我们可以接受。", "Zhèxiē tiáojiàn wǒmen kěyǐ jiēshòu.", "We can accept these terms.")),
            ("让步", "ràngbù", "to compromise / concession",
             ("双方都需要让步。", "Shuāngfāng dōu xūyào ràngbù.", "Both sides need to compromise."),
             ("我们在价格上做了让步。", "Wǒmen zài jiàgé shàng zuò le ràngbù.", "We made a concession on price.")),
            ("合作", "hézuò", "cooperation / partnership",
             ("我们希望长期合作。", "Wǒmen xīwàng chángqī hézuò.", "We hope for long-term cooperation."),
             ("合作对双方都有利。", "Hézuò duì shuāngfāng dōu yǒulì.", "Cooperation benefits both parties.")),
            ("方案", "fāng'àn", "proposal / plan",
             ("请提交新的方案。", "Qǐng tíjiāo xīn de fāng'àn.", "Please submit a new proposal."),
             ("这个方案更可行。", "Zhège fāng'àn gèng kěxíng.", "This plan is more feasible.")),
            ("底线", "dǐxiàn", "bottom line",
             ("这是我们的底线。", "Zhè shì wǒmen de dǐxiàn.", "This is our bottom line."),
             ("价格不能低于底线。", "Jiàgé bùnéng dī yú dǐxiàn.", "The price cannot go below our bottom line.")),
            ("共识", "gòngshí", "consensus",
             ("双方达成了共识。", "Shuāngfāng dáchéng le gòngshí.", "Both sides reached a consensus."),
             ("还需要进一步达成共识。", "Hái xūyào jìnyībù dáchéng gòngshí.", "We still need to build more consensus.")),
            ("条款", "tiáokuǎn", "clause / provision",
             ("请仔细审查合同条款。", "Qǐng zǐxì shěnchá hétong tiáokuǎn.", "Please review the contract clauses carefully."),
             ("这一条款需要修改。", "Zhè yī tiáokuǎn xūyào xiūgǎi.", "This clause needs to be revised.")),
            ("利益", "lìyì", "interest / benefit",
             ("要兼顾双方利益。", "Yào jiāgù shuāngfāng lìyì.", "We must consider both parties' interests."),
             ("这个决定对利益很大。", "Zhège juédìng duì lìyì hěn dà.", "This decision greatly affects our interests.")),
            ("僵局", "jiāngjú", "deadlock / stalemate",
             ("谈判陷入了僵局。", "Tánpàn xiànrù le jiāngjú.", "The negotiation has reached a deadlock."),
             ("我们需要打破僵局。", "Wǒmen xūyào dǎpò jiāngjú.", "We need to break the stalemate.")),
        ],
        "contracts": [
            ("合同", "hétong", "contract",
             ("请签署合同。", "Qǐng qiānshǔ hétong.", "Please sign the contract."),
             ("合同有效期一年。", "Hétong yǒuxiàoqī yī nián.", "The contract is valid for one year.")),
            ("签署", "qiānshǔ", "to sign",
             ("双方今天签署协议。", "Shuāngfāng jīntiān qiānshǔ xiéyì.", "Both parties sign the agreement today."),
             ("请在最后一页签署。", "Qǐng zài zuìhòu yī yè qiānshǔ.", "Please sign on the last page.")),
            ("条款", "tiáokuǎn", "clause",
             ("合同条款很详细。", "Hétong tiáokuǎn hěn xiángxì.", "The contract clauses are detailed."),
             ("请修改第三条条款。", "Qǐng xiūgǎi dì sān tiáo tiáokuǎn.", "Please revise clause three.")),
            ("违约", "wéiyuē", "breach of contract",
             ("违约需要赔偿。", "Wéiyuē xūyào péicháng.", "Breach of contract requires compensation."),
             ("对方可能违约了。", "Duìfāng kěnéng wéiyuē le.", "The other party may have breached the contract.")),
            ("生效", "shēngxiào", "to take effect",
             ("合同下月生效。", "Hétong xià yuè shēngxiào.", "The contract takes effect next month."),
             ("协议已经生效了。", "Xiéyì yǐjīng shēngxiào le.", "The agreement is already in effect.")),
            ("续签", "xùqiān", "to renew (a contract)",
             ("我们想续签合同。", "Wǒmen xiǎng xùqiān hétong.", "We'd like to renew the contract."),
             ("合同快到期了，要续签。", "Hétong kuài dàoqī le, yào xùqiān.", "The contract is expiring soon and needs renewal.")),
            ("保密", "bǎomì", "confidential / NDA",
             ("请遵守保密协议。", "Qǐng zūnshǒu bǎomì xiéyì.", "Please abide by the confidentiality agreement."),
             ("这些资料需要保密。", "Zhèxiē zīliào xūyào bǎomì.", "This information must be kept confidential.")),
            ("附件", "fùjiàn", "appendix / attachment",
             ("合同附件同样有效。", "Hétong fùjiàn tóngyàng yǒuxiào.", "Contract appendices are equally binding."),
             ("请看合同附件二。", "Qǐng kàn hétong fùjiàn èr.", "Please see contract appendix two.")),
            ("甲方", "jiǎfāng", "Party A (contract)",
             ("甲方负责提供设备。", "Jiǎfāng fùzé tígōng shèbèi.", "Party A is responsible for providing equipment."),
             ("甲方代表已经签字了。", "Jiǎfāng dàibiǎo yǐjīng qiānzì le.", "Party A's representative has signed.")),
            ("乙方", "yǐfāng", "Party B (contract)",
             ("乙方需要在三十天内交付。", "Yǐfāng xūyào zài sānshí tiān nèi jiāofù.", "Party B must deliver within thirty days."),
             ("乙方同意以上条款。", "Yǐfāng tóngyì yǐshàng tiáokuǎn.", "Party B agrees to the above terms.")),
        ],
    }
    return _flatten_sections(data)


def _flatten_sections(data: dict[str, list[WordTuple]]) -> list[dict]:
    output: list[dict] = []
    for section, words in data.items():
        if len(words) != 10:
            raise ValueError(f"{section} must have 10 words, got {len(words)}")
        output.extend(section_words(section, words))
    return output


def build_daily_life() -> list[dict]:
    data = {
        "greetings": [
            ("早上好", "zǎoshang hǎo", "good morning",
             ("早上好，今天天气不错。", "Zǎoshang hǎo, jīntiān tiānqì búcuò.", "Good morning, the weather is nice today."),
             ("她每天早上好地跟邻居打招呼。", "Tā měitiān zǎoshang hǎo de gēn línjū dǎ zhāohu.", "She greets her neighbors good morning every day.")),
            ("晚上好", "wǎnshang hǎo", "good evening",
             ("晚上好，欢迎光临。", "Wǎnshang hǎo, huānyíng guānglín.", "Good evening, welcome."),
             ("晚上好，吃饭了吗？", "Wǎnshang hǎo, chīfàn le ma?", "Good evening, have you eaten?")),
            ("再见", "zàijiàn", "goodbye",
             ("再见，明天见。", "Zàijiàn, míngtiān jiàn.", "Goodbye, see you tomorrow."),
             ("我先走了，再见。", "Wǒ xiān zǒu le, zàijiàn.", "I'm leaving now, goodbye.")),
            ("请多关照", "qǐng duō guānzhào", "please take care of me (polite)",
             ("初来乍到，请多关照。", "Chūlái zhàdào, qǐng duō guānzhào.", "I'm new here, please look after me."),
             ("以后请多关照。", "Yǐhòu qǐng duō guānzhào.", "Please take care of me in the future.")),
            ("久仰", "jiǔyǎng", "I've heard so much about you",
             ("久仰大名。", "Jiǔyǎng dàmíng.", "I've long admired your reputation."),
             ("久仰，终于见面了。", "Jiǔyǎng, zhōngyú jiànmiàn le.", "I've heard so much about you, finally we meet.")),
            ("最近怎么样", "zuìjìn zěnmeyàng", "how have you been lately",
             ("最近怎么样？", "Zuìjìn zěnmeyàng?", "How have you been lately?"),
             ("好久不见，最近怎么样？", "Hǎojiǔ bú jiàn, zuìjìn zěnmeyàng?", "Long time no see, how have you been?")),
            ("欢迎", "huānyíng", "welcome",
             ("欢迎来到北京。", "Huānyíng lái dào Běijīng.", "Welcome to Beijing."),
             ("欢迎大家参加。", "Huānyíng dàjiā cānjiā.", "Welcome everyone to join.")),
            ("恭喜", "gōngxǐ", "congratulations",
             ("恭喜你升职了。", "Gōngxǐ nǐ shēngzhí le.", "Congratulations on your promotion."),
             ("恭喜发财！", "Gōngxǐ fācái!", "Wishing you prosperity!")),
            ("节日快乐", "jiérì kuàilè", "happy holiday",
             ("祝你节日快乐。", "Zhù nǐ jiérì kuàilè.", "Happy holidays to you."),
             ("节日快乐，阖家幸福。", "Jiérì kuàilè, héjiā xìngfú.", "Happy holidays and happiness to your family.")),
            ("慢走", "mànzǒu", "take care (when seeing someone off)",
             ("谢谢，慢走。", "Xièxie, mànzǒu.", "Thank you, take care."),
             ("天黑了，慢走啊。", "Tiān hēi le, mànzǒu a.", "It's dark out, take care on your way.")),
        ],
        "family": [
            ("爸爸", "bàba", "dad / father",
             ("我爸爸是医生。", "Wǒ bàba shì yīshēng.", "My dad is a doctor."),
             ("爸爸今天加班。", "Bàba jīntiān jiābān.", "Dad is working overtime today.")),
            ("妈妈", "māma", "mom / mother",
             ("妈妈做的饭最好吃。", "Māma zuò de fàn zuì hǎochī.", "Mom's cooking is the best."),
             ("我给妈妈买了礼物。", "Wǒ gěi māma mǎi le lǐwù.", "I bought a gift for mom.")),
            ("孩子", "háizi", "child",
             ("他们有两个孩子。", "Tāmen yǒu liǎng gè háizi.", "They have two children."),
             ("孩子在客厅玩。", "Háizi zài kètīng wán.", "The child is playing in the living room.")),
            ("爷爷", "yéye", "grandfather (paternal)",
             ("爷爷今年七十岁了。", "Yéye jīnnián qīshí suì le.", "Grandpa is seventy this year."),
             ("周末我去看爷爷。", "Zhōumò wǒ qù kàn yéye.", "I'm visiting grandpa on the weekend.")),
            ("奶奶", "nǎinai", "grandmother (paternal)",
             ("奶奶身体很健康。", "Nǎinai shēntǐ hěn jiànkāng.", "Grandma is in good health."),
             ("奶奶在厨房做饭。", "Nǎinai zài chúfáng zuòfàn.", "Grandma is cooking in the kitchen.")),
            ("哥哥", "gēge", "older brother",
             ("我哥哥在大学读书。", "Wǒ gēge zài dàxué dúshū.", "My older brother is in university."),
             ("哥哥比我大三岁。", "Gēge bǐ wǒ dà sān suì.", "My brother is three years older than me.")),
            ("姐姐", "jiějie", "older sister",
             ("姐姐在上海工作。", "Jiějie zài Shànghǎi gōngzuò.", "My older sister works in Shanghai."),
             ("姐姐教我学英语。", "Jiějie jiāo wǒ xué Yīngyǔ.", "My sister teaches me English.")),
            ("丈夫", "zhàngfu", "husband",
             ("我丈夫是工程师。", "Wǒ zhàngfu shì gōngchéngshī.", "My husband is an engineer."),
             ("丈夫在家带孩子。", "Zhàngfu zài jiā dài háizi.", "My husband is home with the kids.")),
            ("妻子", "qīzi", "wife",
             ("他妻子是老师。", "Tā qīzi shì lǎoshī.", "His wife is a teacher."),
             ("我和妻子一起去旅行。", "Wǒ hé qīzi yīqǐ qù lǚxíng.", "My wife and I are traveling together.")),
            ("亲戚", "qīnqi", "relative",
             ("春节亲戚都会来。", "Chūnjié qīnqi dōu huì lái.", "Relatives all come during Spring Festival."),
             ("他是我远房亲戚。", "Tā shì wǒ yuǎnfáng qīnqi.", "He's a distant relative of mine.")),
        ],
        "home": [
            ("客厅", "kètīng", "living room",
             ("大家在客厅看电视。", "Dàjiā zài kètīng kàn diànshì.", "Everyone is watching TV in the living room."),
             ("客厅很宽敞。", "Kètīng hěn kuānchang.", "The living room is spacious.")),
            ("卧室", "wòshì", "bedroom",
             ("我的卧室在二楼。", "Wǒ de wòshì zài èr lóu.", "My bedroom is on the second floor."),
             ("请保持卧室整洁。", "Qǐng bǎochí wòshì zhěngjié.", "Please keep the bedroom tidy.")),
            ("厨房", "chúfáng", "kitchen",
             ("厨房里有新设备。", "Chúfáng lǐ yǒu xīn shèbèi.", "There's new equipment in the kitchen."),
             ("她在厨房准备晚餐。", "Tā zài chúfáng zhǔnbèi wǎncān.", "She's preparing dinner in the kitchen.")),
            ("卫生间", "wèishēngjiān", "bathroom",
             ("请用里面的卫生间。", "Qǐng yòng lǐmiàn de wèishēngjiān.", "Please use the bathroom inside."),
             ("卫生间需要打扫了。", "Wèishēngjiān xūyào dǎsǎo le.", "The bathroom needs cleaning.")),
            ("阳台", "yángtái", "balcony",
             ("阳台上种了花。", "Yángtái shàng zhòng le huā.", "Flowers are planted on the balcony."),
             ("请到阳台晾衣服。", "Qǐng dào yángtái liàng yīfu.", "Please hang clothes on the balcony.")),
            ("钥匙", "yàoshi", "key",
             ("我的钥匙忘带了。", "Wǒ de yàoshi wàng dài le.", "I forgot my keys."),
             ("请把钥匙放在门口。", "Qǐng bǎ yàoshi fàng zài ménkǒu.", "Please leave the keys at the door.")),
            ("打扫", "dǎsǎo", "to clean",
             ("今天我要打扫房间。", "Jīntiān wǒ yào dǎsǎo fángjiān.", "I'm cleaning the room today."),
             ("我们每周六打扫。", "Wǒmen měi zhōuliù dǎsǎo.", "We clean every Saturday.")),
            ("修理", "xiūlǐ", "to repair / fix",
             ("空调需要修理了。", "Kōngtiáo xūyào xiūlǐ le.", "The AC needs repair."),
             ("他帮我把水龙头修好了。", "Tā bāng wǒ bǎ shuǐlóngtóu xiū hǎo le.", "He fixed the faucet for me.")),
            ("邻居", "línjū", "neighbor",
             ("我的邻居很友好。", "Wǒ de línjū hěn yǒuhǎo.", "My neighbors are friendly."),
             ("邻居借给我一把伞。", "Línjū jiè gěi wǒ yī bǎ sǎn.", "My neighbor lent me an umbrella.")),
            ("房租", "fángzū", "rent",
             ("房租每月三千块。", "Fángzū měi yuè sān qiān kuài.", "Rent is three thousand a month."),
             ("房租该交了。", "Fángzū gāi jiāo le.", "It's time to pay the rent.")),
        ],
        "shopping": [
            ("超市", "chāoshì", "supermarket",
             ("我去超市买菜。", "Wǒ qù chāoshì mǎi cài.", "I'm going to the supermarket for groceries."),
             ("这家超市很大。", "Zhè jiā chāoshì hěn dà.", "This supermarket is very big.")),
            ("购物车", "gòuwùchē", "shopping cart",
             ("请推一辆购物车。", "Qǐng tuī yī liàng gòuwùchē.", "Please get a shopping cart."),
             ("购物车满了。", "Gòuwùchē mǎn le.", "The cart is full.")),
            ("打折", "dǎzhé", "discount / on sale",
             ("这件衣服打折了。", "Zhè jiàn yīfu dǎzhé le.", "This item is on sale."),
             ("今天全场八折。", "Jīntiān quánchǎng bā zhé.", "Everything is twenty percent off today.")),
            ("排队", "páiduì", "to queue / line up",
             ("收银台在排队。", "Shōuyíntái zài páiduì.", "There's a line at checkout."),
             ("请在这里排队。", "Qǐng zài zhèlǐ páiduì.", "Please queue here.")),
            ("称重", "chēngzhòng", "to weigh",
             ("请在柜台称重。", "Qǐng zài guìtái chēngzhòng.", "Please weigh it at the counter."),
             ("水果需要先称重。", "Shuǐguǒ xūyào xiān chēngzhòng.", "Fruit needs to be weighed first.")),
            ("保质期", "bǎozhìqī", "shelf life / expiration date",
             ("请看一下保质期。", "Qǐng kàn yīxià bǎozhìqī.", "Please check the expiration date."),
             ("这牛奶保质期过了。", "Zhè niúnǎi bǎozhìqī guò le.", "This milk is past its expiration date.")),
            ("退货", "tuìhuò", "to return goods",
             ("我可以退货吗？", "Wǒ kěyǐ tuìhuò ma?", "Can I return this item?"),
             ("七天内可以退货。", "Qī tiān nèi kěyǐ tuìhuò.", "Returns accepted within seven days.")),
            ("会员", "huìyuán", "member / membership",
             ("办会员有积分。", "Bàn huìyuán yǒu jīfēn.", "Members earn points."),
             ("请出示会员卡。", "Qǐng chūshì huìyuán kǎ.", "Please show your membership card.")),
            ("零钱", "língqián", "small change",
             ("你有零钱吗？", "Nǐ yǒu língqián ma?", "Do you have small change?"),
             ("我换了些零钱。", "Wǒ huàn le xiē língqián.", "I got some small change.")),
            ("购物袋", "gòuwùdài", "shopping bag",
             ("需要购物袋吗？", "Xūyào gòuwùdài ma?", "Do you need a shopping bag?"),
             ("我自带了购物袋。", "Wǒ zìdài le gòuwùdài.", "I brought my own shopping bag.")),
        ],
        "weather": [
            ("晴天", "qíngtiān", "sunny day",
             ("今天是晴天。", "Jīntiān shì qíngtiān.", "It's sunny today."),
             ("晴天适合出去玩。", "Qíngtiān shìhé chūqù wán.", "Sunny days are good for going out.")),
            ("下雨", "xiàyǔ", "to rain",
             ("外面下雨了。", "Wàimiàn xiàyǔ le.", "It's raining outside."),
             ("下午可能会下雨。", "Xiàwǔ kěnéng huì xiàyǔ.", "It might rain this afternoon.")),
            ("下雪", "xiàxuě", "to snow",
             ("北方下雪了。", "Běifāng xiàxuě le.", "It's snowing in the north."),
             ("孩子们喜欢下雪。", "Háizimen xǐhuan xiàxuě.", "Kids love snow.")),
            ("刮风", "guāfēng", "windy / to blow wind",
             ("今天风很大。", "Jīntiān fēng hěn dà.", "It's very windy today."),
             ("别出门，外面刮风了。", "Bié chūmén, wàimiàn guāfēng le.", "Don't go out, it's windy.")),
            ("温度", "wēndù", "temperature",
             ("今天温度很高。", "Jīntiān wēndù hěn gāo.", "The temperature is high today."),
             ("请看一下温度。", "Qǐng kàn yīxià wēndù.", "Please check the temperature.")),
            ("预报", "yùbào", "forecast",
             ("天气预报说会降温。", "Tiānqì yùbào shuō huì jiàngwēn.", "The forecast says it will cool down."),
             ("请听一下天气预报。", "Qǐng tīng yīxià tiānqì yùbào.", "Please listen to the weather forecast.")),
            ("潮湿", "cháoshī", "humid / damp",
             ("南方夏天很潮湿。", "Nánfāng xiàtiān hěn cháoshī.", "Summers in the south are humid."),
             ("房间有点潮湿。", "Fángjiān yǒudiǎn cháoshī.", "The room is a bit damp.")),
            ("干燥", "gānzào", "dry",
             ("秋天天气干燥。", "Qiūtiān tiānqì gānzào.", "The weather is dry in autumn."),
             ("北方冬天很干燥。", "Běifāng dōngtiān hěn gānzào.", "Winters in the north are very dry.")),
            ("阴天", "yīntiān", "cloudy / overcast",
             ("今天是阴天。", "Jīntiān shì yīntiān.", "It's overcast today."),
             ("阴天人比较少。", "Yīntiān rén bǐjiào shǎo.", "There are fewer people on cloudy days.")),
            ("台风", "táifēng", "typhoon",
             ("台风要来了。", "Táifēng yào lái le.", "A typhoon is coming."),
             ("台风天不要出门。", "Táifēng tiān bú yào chūmén.", "Don't go out during a typhoon.")),
        ],
        "time": [
            ("现在", "xiànzài", "now",
             ("现在几点了？", "Xiànzài jǐ diǎn le?", "What time is it now?"),
             ("我现在很忙。", "Wǒ xiànzài hěn máng.", "I'm very busy now.")),
            ("今天", "jīntiān", "today",
             ("今天是星期一。", "Jīntiān shì xīngqīyī.", "Today is Monday."),
             ("今天我有空。", "Jīntiān wǒ yǒu kòng.", "I'm free today.")),
            ("明天", "míngtiān", "tomorrow",
             ("明天见。", "Míngtiān jiàn.", "See you tomorrow."),
             ("明天要早起。", "Míngtiān yào zǎo qǐ.", "I need to get up early tomorrow.")),
            ("昨天", "zuótiān", "yesterday",
             ("我昨天去了北京。", "Wǒ zuótiān qù le Běijīng.", "I went to Beijing yesterday."),
             ("昨天下了雨。", "Zuótiān xià le yǔ.", "It rained yesterday.")),
            ("周末", "zhōumò", "weekend",
             ("周末你做什么？", "Zhōumò nǐ zuò shénme?", "What do you do on weekends?"),
             ("我们周末去爬山。", "Wǒmen zhōumò qù pá shān.", "We're hiking on the weekend.")),
            ("分钟", "fēnzhōng", "minute",
             ("请等我五分钟。", "Qǐng děng wǒ wǔ fēnzhōng.", "Please wait five minutes for me."),
             ("还有十分钟开始。", "Hái yǒu shí fēnzhōng kāishǐ.", "It starts in ten minutes.")),
            ("小时", "xiǎoshí", "hour",
             ("我睡了一个小时。", "Wǒ shuì le yī gè xiǎoshí.", "I slept for an hour."),
             ("开车要两个小时。", "Kāichē yào liǎng gè xiǎoshí.", "The drive takes two hours.")),
            ("准时", "zhǔnshí", "on time",
             ("请准时到达。", "Qǐng zhǔnshí dàodá.", "Please arrive on time."),
             ("火车准时出发了。", "Huǒchē zhǔnshí chūfā le.", "The train departed on time.")),
            ("日历", "rìlì", "calendar",
             ("看一下日历。", "Kàn yīxià rìlì.", "Check the calendar."),
             ("日历上标注了假期。", "Rìlì shàng biāozhù le jiàqī.", "Holidays are marked on the calendar.")),
            ("生日", "shēngrì", "birthday",
             ("今天是我的生日。", "Jīntiān shì wǒ de shēngrì.", "Today is my birthday."),
             ("祝你生日快乐。", "Zhù nǐ shēngrì kuàilè.", "Happy birthday to you.")),
        ],
        "emotions": [
            ("高兴", "gāoxìng", "happy / glad",
             ("听到这个消息我很高兴。", "Tīngdào zhège xiāoxi wǒ hěn gāoxìng.", "I'm glad to hear this news."),
             ("今天心情很高兴。", "Jīntiān xīnqíng hěn gāoxìng.", "I'm in a happy mood today.")),
            ("难过", "nánguò", "sad / upset",
             ("他看起来很难过。", "Tā kàn qǐlái hěn nánguò.", "He looks very sad."),
             ("别难过，会好起来的。", "Bié nánguò, huì hǎo qǐlái de.", "Don't be sad, things will get better.")),
            ("生气", "shēngqì", "angry",
             ("请不要生气。", "Qǐng bú yào shēngqì.", "Please don't be angry."),
             ("他对结果很生气。", "Tā duì jiéguǒ hěn shēngqì.", "He's angry about the result.")),
            ("担心", "dānxīn", "to worry",
             ("别担心，有我。", "Bié dānxīn, yǒu wǒ.", "Don't worry, I'm here."),
             ("妈妈很担心你。", "Māma hěn dānxīn nǐ.", "Mom is worried about you.")),
            ("紧张", "jǐnzhāng", "nervous / tense",
             ("考试前我很紧张。", "Kǎoshì qián wǒ hěn jǐnzhāng.", "I'm nervous before exams."),
             ("别紧张，慢慢来。", "Bié jǐnzhāng, mànman lái.", "Don't be nervous, take your time.")),
            ("放松", "fàngsōng", "to relax",
             ("周末好好放松。", "Zhōumò hǎohao fàngsōng.", "Relax properly on the weekend."),
             ("听音乐可以放松。", "Tīng yīnyuè kěyǐ fàngsōng.", "Listening to music helps you relax.")),
            ("感动", "gǎndòng", "moved / touched",
             ("这个故事很感人。", "Zhège gùshi hěn gǎnrén.", "This story is very touching."),
             ("我被他的帮助感动了。", "Wǒ bèi tā de bāngzhù gǎndòng le.", "I was moved by his help.")),
            ("无聊", "wúliáo", "bored",
             ("在家太无聊了。", "Zài jiā tài wúliáo le.", "Staying home is so boring."),
             ("这部电影很无聊。", "Zhè bù diànyǐng hěn wúliáo.", "This movie is boring.")),
            ("兴奋", "xīngfèn", "excited",
             ("孩子们很兴奋。", "Háizimen hěn xīngfèn.", "The kids are excited."),
             ("我对旅行很兴奋。", "Wǒ duì lǚxíng hěn xīngfèn.", "I'm excited about the trip.")),
            ("满足", "mǎnzú", "satisfied / content",
             ("我对结果很满足。", "Wǒ duì jiéguǒ hěn mǎnzú.", "I'm satisfied with the result."),
             ("简单的生活也很满足。", "Jiǎndān de shēnghuó yě hěn mǎnzú.", "A simple life can be fulfilling too.")),
        ],
        "clothing": [
            ("衣服", "yīfu", "clothes",
             ("这件衣服很好看。", "Zhè jiàn yīfu hěn hǎokàn.", "These clothes look nice."),
             ("我在洗衣服。", "Wǒ zài xǐ yīfu.", "I'm doing laundry.")),
            ("裤子", "kùzi", "pants / trousers",
             ("这条裤子太长了。", "Zhè tiáo kùzi tài cháng le.", "These pants are too long."),
             ("他买了一条新裤子。", "Tā mǎi le yī tiáo xīn kùzi.", "He bought new pants.")),
            ("鞋子", "xiézi", "shoes",
             ("这双鞋子很舒服。", "Zhè shuāng xiézi hěn shūfu.", "These shoes are comfortable."),
             ("我的鞋子脏了。", "Wǒ de xiézi zāng le.", "My shoes are dirty.")),
            ("外套", "wàitào", "jacket / coat",
             ("外面冷，穿外套。", "Wàimiàn lěng, chuān wàitào.", "It's cold outside, wear a jacket."),
             ("我把外套忘在餐厅了。", "Wǒ bǎ wàitào wàng zài cāntīng le.", "I left my jacket at the restaurant.")),
            ("尺寸", "chǐcùn", "size",
             ("请问有大一点的尺寸吗？", "Qǐngwèn yǒu dà yīdiǎn de chǐcùn ma?", "Do you have a larger size?"),
             ("尺寸很合适。", "Chǐcùn hěn héshì.", "The size fits well.")),
            ("试穿", "shìchuān", "to try on",
             ("我可以试穿吗？", "Wǒ kěyǐ shìchuān ma?", "Can I try this on?"),
             ("请去试衣间试穿。", "Qǐng qù shìyījiān shìchuān.", "Please try it on in the fitting room.")),
            ("洗衣", "xǐyī", "laundry / to wash clothes",
             ("我把衣服送去洗衣了。", "Wǒ bǎ yīfu sòng qù xǐyī le.", "I sent the clothes to the laundry."),
             ("洗衣店在楼下。", "Xǐyīdiàn zài lóu xià.", "The laundry shop is downstairs.")),
            ("帽子", "màozi", "hat / cap",
             ("夏天要戴帽子。", "Xiàtiān yào dài màozi.", "Wear a hat in summer."),
             ("他的帽子是蓝色的。", "Tā de màozi shì lánsè de.", "His hat is blue.")),
            ("围巾", "wéijīn", "scarf",
             ("冬天围巾很必要。", "Dōngtiān wéijīn hěn bìyào.", "A scarf is essential in winter."),
             ("她送了我一条围巾。", "Tā sòng le wǒ yī tiáo wéijīn.", "She gave me a scarf.")),
            ("搭配", "dāpèi", "to match / outfit coordination",
             ("这套搭配很好看。", "Zhè tào dāpèi hěn hǎokàn.", "This outfit looks great."),
             ("黑色很容易搭配。", "Hēisè hěn róngyì dāpèi.", "Black is easy to match.")),
        ],
        "health": [
            ("健康", "jiànkāng", "health / healthy",
             ("健康最重要。", "Jiànkāng zuì zhòngyào.", "Health is most important."),
             ("他身体很健康。", "Tā shēntǐ hěn jiànkāng.", "He's in good health.")),
            ("感冒", "gǎnmào", "cold (illness)",
             ("我感冒了。", "Wǒ gǎnmào le.", "I caught a cold."),
             ("多喝水，别感冒。", "Duō hē shuǐ, bié gǎnmào.", "Drink more water so you don't catch a cold.")),
            ("发烧", "fāshāo", "fever",
             ("孩子发烧了。", "Háizi fāshāo le.", "The child has a fever."),
             ("我发烧三十八度。", "Wǒ fāshāo sānshíbā dù.", "I have a fever of 38°C.")),
            ("头痛", "tóutòng", "headache",
             ("我头痛得厉害。", "Wǒ tóutòng de lìhai.", "I have a bad headache."),
             ("熬夜会头痛。", "Áoyè huì tóutòng.", "Staying up late gives you headaches.")),
            ("锻炼", "duànliàn", "to exercise",
             ("我每天锻炼半小时。", "Wǒ měitiān duànliàn bàn xiǎoshí.", "I exercise half an hour daily."),
             ("锻炼对身体好。", "Duànliàn duì shēntǐ hǎo.", "Exercise is good for your body.")),
            ("休息", "xiūxi", "to rest",
             ("你需要好好休息。", "Nǐ xūyào hǎohao xiūxi.", "You need to rest properly."),
             ("周末我在家休息。", "Zhōumò wǒ zài jiā xiūxi.", "I rest at home on weekends.")),
            ("药", "yào", "medicine",
             ("请按时吃药。", "Qǐng ànshí chī yào.", "Please take your medicine on time."),
             ("这种药很有效。", "Zhè zhǒng yào hěn yǒuxiào.", "This medicine works well.")),
            ("预约", "yùyuē", "appointment / to book",
             ("我预约了医生。", "Wǒ yùyuē le yīshēng.", "I made a doctor's appointment."),
             ("请提前预约体检。", "Qǐng tíqián yùyuē tǐjiǎn.", "Please book a check-up in advance.")),
            ("过敏", "guòmǐn", "allergy",
             ("我对海鲜过敏。", "Wǒ duì hǎixiān guòmǐn.", "I'm allergic to seafood."),
             ("春天容易过敏。", "Chūntiān róngyì guòmǐn.", "Allergies are common in spring.")),
            ("睡眠", "shuìmián", "sleep",
             ("睡眠很重要。", "Shuìmián hěn zhòngyào.", "Sleep is important."),
             ("我昨晚睡眠不好。", "Wǒ zuó wǎn shuìmián bù hǎo.", "I didn't sleep well last night.")),
        ],
        "social": [
            ("朋友", "péngyou", "friend",
             ("他是我的好朋友。", "Tā shì wǒ de hǎo péngyou.", "He's my good friend."),
             ("周末和朋友聚会。", "Zhōumò hé péngyou jùhuì.", "I'm meeting friends on the weekend.")),
            ("聚会", "jùhuì", "gathering / party",
             ("今晚有个聚会。", "Jīn wǎn yǒu gè jùhuì.", "There's a gathering tonight."),
             ("同学聚会很开心。", "Tóngxué jùhuì hěn kāixīn.", "The class reunion was fun.")),
            ("邀请", "yāoqǐng", "to invite",
             ("我邀请你来我家。", "Wǒ yāoqǐng nǐ lái wǒ jiā.", "I invite you to my home."),
             ("谢谢你的邀请。", "Xièxie nǐ de yāoqǐng.", "Thank you for the invitation.")),
            ("聊天", "liáotiān", "to chat",
             ("我们在网上聊天。", "Wǒmen zài wǎngshàng liáotiān.", "We chat online."),
             ("喜欢和朋友聊天。", "Xǐhuan hé péngyou liáotiān.", "I like chatting with friends.")),
            ("爱好", "àihào", "hobby",
             ("你的爱好是什么？", "Nǐ de àihào shì shénme?", "What are your hobbies?"),
             ("我的爱好是摄影。", "Wǒ de àihào shì shèyǐng.", "My hobby is photography.")),
            ("约会", "yuēhuì", "date / appointment (social)",
             ("他们今晚有约会。", "Tāmen jīn wǎn yǒu yuēhuì.", "They have a date tonight."),
             ("我约了朋友喝咖啡。", "Wǒ yuē le péngyou hē kāfēi.", "I made plans to have coffee with a friend.")),
            ("介绍", "jièshào", "to introduce",
             ("请介绍一下你自己。", "Qǐng jièshào yīxià nǐ zìjǐ.", "Please introduce yourself."),
             ("我介绍你们认识。", "Wǒ jièshào nǐmen rènshi.", "Let me introduce you two.")),
            ("礼物", "lǐwù", "gift",
             ("这是我给你的礼物。", "Zhè shì wǒ gěi nǐ de lǐwù.", "This is a gift for you."),
             ("谢谢你的礼物。", "Xièxie nǐ de lǐwù.", "Thank you for the gift.")),
            ("祝福", "zhùfú", "blessing / well wishes",
             ("祝你新婚祝福。", "Zhù nǐ xīnhūn zhùfú.", "Best wishes on your wedding."),
             ("收到很多祝福。", "Shōudào hěn duō zhùfú.", "I received many well wishes.")),
            ("社交", "shèjiāo", "social / socializing",
             ("我不太喜欢社交。", "Wǒ bú tài xǐhuan shèjiāo.", "I don't really like socializing."),
             ("社交能力很重要。", "Shèjiāo nénglì hěn zhòngyào.", "Social skills are important.")),
        ],
    }
    return _flatten_sections(data)


def build_food() -> list[dict]:
    data = {
        "fruits": [
            ("苹果", "píngguǒ", "apple",
             ("我每天吃一个苹果。", "Wǒ měitiān chī yī gè píngguǒ.", "I eat an apple every day."),
             ("这些苹果很甜。", "Zhèxiē píngguǒ hěn tián.", "These apples are very sweet.")),
            ("香蕉", "xiāngjiāo", "banana",
             ("香蕉放久了会变黑。", "Xiāngjiāo fàng jiǔ le huì biàn hēi.", "Bananas turn black if kept too long."),
             ("孩子喜欢吃香蕉。", "Háizi xǐhuan chī xiāngjiāo.", "Kids like eating bananas.")),
            ("橙子", "chéngzi", "orange",
             ("橙子维生素很丰富。", "Chéngzi wéishēngsù hěn fēngfù.", "Oranges are rich in vitamins."),
             ("请给我两个橙子。", "Qǐng gěi wǒ liǎng gè chéngzi.", "Please give me two oranges.")),
            ("葡萄", "pútáo", "grape",
             ("这串葡萄很大。", "Zhè chuàn pútáo hěn dà.", "This bunch of grapes is big."),
             ("夏天葡萄最好吃。", "Xiàtiān pútáo zuì hǎochī.", "Grapes taste best in summer.")),
            ("西瓜", "xīguā", "watermelon",
             ("夏天吃西瓜很解暑。", "Xiàtiān chī xīguā hěn jiěshǔ.", "Watermelon is refreshing in summer."),
             ("这个西瓜很甜。", "Zhège xīguā hěn tián.", "This watermelon is sweet.")),
            ("草莓", "cǎoméi", "strawberry",
             ("草莓蛋糕很受欢迎。", "Cǎoméi dàngāo hěn shòu huānyíng.", "Strawberry cake is popular."),
             ("新鲜的草莓红了。", "Xīnxiān de cǎoméi hóng le.", "Fresh strawberries have turned red.")),
            ("桃子", "táozi", "peach",
             ("桃子熟了很香。", "Táozi shú le hěn xiāng.", "Ripe peaches smell wonderful."),
             ("我买了三斤桃子。", "Wǒ mǎi le sān jīn táozi.", "I bought three jin of peaches.")),
            ("梨", "lí", "pear",
             ("这种梨水分很多。", "Zhè zhǒng lí shuǐfèn hěn duō.", "This type of pear is very juicy."),
             ("冬天吃梨对嗓子好。", "Dōngtiān chī lí duì sǎngzi hǎo.", "Eating pears in winter is good for your throat.")),
            ("芒果", "mángguǒ", "mango",
             ("芒果是热带水果。", "Mángguǒ shì rèdài shuǐguǒ.", "Mangoes are tropical fruit."),
             ("我喜欢芒果的味道。", "Wǒ xǐhuan mángguǒ de wèidào.", "I like the taste of mango.")),
            ("樱桃", "yīngtáo", "cherry",
             ("樱桃季节很短。", "Yīngtáo jìjié hěn duǎn.", "Cherry season is short."),
             ("这些樱桃很新鲜。", "Zhèxiē yīngtáo hěn xīnxiān.", "These cherries are very fresh.")),
        ],
        "vegetables": [
            ("白菜", "báicài", "Chinese cabbage",
             ("白菜可以炒也可以煮。", "Báicài kěyǐ chǎo yě kěyǐ zhǔ.", "Cabbage can be stir-fried or boiled."),
             ("我要一棵白菜。", "Wǒ yào yī kē báicài.", "I'd like one head of cabbage.")),
            ("西红柿", "xīhóngshì", "tomato",
             ("西红柿炒鸡蛋很好吃。", "Xīhóngshì chǎo jīdàn hěn hǎochī.", "Tomato and egg stir-fry is delicious."),
             ("这些西红柿很红。", "Zhèxiē xīhóngshì hěn hóng.", "These tomatoes are very red.")),
            ("土豆", "tǔdòu", "potato",
             ("我喜欢吃炸土豆。", "Wǒ xǐhuan chī zhá tǔdòu.", "I like fried potatoes."),
             ("土豆可以做成很多菜。", "Tǔdòu kěyǐ zuò chéng hěn duō cài.", "Potatoes can be made into many dishes.")),
            ("胡萝卜", "húluóbo", "carrot",
             ("胡萝卜对眼睛好。", "Húluóbo duì yǎnjing hǎo.", "Carrots are good for your eyes."),
             ("请切一些胡萝卜。", "Qǐng qiē yīxiē húluóbo.", "Please cut some carrots.")),
            ("黄瓜", "huángguā", "cucumber",
             ("夏天吃黄瓜很清爽。", "Xiàtiān chī huángguā hěn qīngshuǎng.", "Cucumber is refreshing in summer."),
             ("我做一个黄瓜沙拉。", "Wǒ zuò yī gè huángguā shālā.", "I'll make a cucumber salad.")),
            ("茄子", "qiézi", "eggplant",
             ("鱼香茄子很下饭。", "Yúxiāng qiézi hěn xiàfàn.", "Yu Xiang eggplant goes well with rice."),
             ("茄子要炒软才好吃。", "Qiézi yào chǎo ruǎn cái hǎochī.", "Eggplant needs to be cooked soft.")),
            ("菠菜", "bōcài", "spinach",
             ("菠菜含铁量高。", "Bōcài hán tiěliàng gāo.", "Spinach is high in iron."),
             ("请给我一把菠菜。", "Qǐng gěi wǒ yī bǎ bōcài.", "Please give me a bunch of spinach.")),
            ("玉米", "yùmǐ", "corn",
             ("煮玉米很香。", "Zhǔ yùmǐ hěn xiāng.", "Boiled corn smells great."),
             ("我买了一根玉米。", "Wǒ mǎi le yī gēn yùmǐ.", "I bought an ear of corn.")),
            ("蘑菇", "mógū", "mushroom",
             ("这个汤里加了蘑菇。", "Zhège tāng lǐ jiā le mógū.", "Mushrooms were added to this soup."),
             ("蘑菇要洗干净。", "Mógū yào xǐ gānjìng.", "Mushrooms need to be washed clean.")),
            ("辣椒", "làjiāo", "chili pepper",
             ("这个菜放了辣椒。", "Zhège cài fàng le làjiāo.", "This dish has chili peppers."),
             ("我不太能吃辣。", "Wǒ bú tài néng chī là.", "I can't handle spicy food well.")),
        ],
        "meat": [
            ("牛肉", "niúròu", "beef", ("牛肉面很受欢迎。", "Niúròu miàn hěn shòu huānyíng.", "Beef noodles are very popular."), ("请给我一斤牛肉。", "Qǐng gěi wǒ yī jīn niúròu.", "Please give me half a kilo of beef.")),
            ("猪肉", "zhūròu", "pork", ("猪肉可以做成很多菜。", "Zhūròu kěyǐ zuò chéng hěn duō cài.", "Pork can be made into many dishes."), ("今天买了新鲜猪肉。", "Jīntiān mǎi le xīnxiān zhūròu.", "We bought fresh pork today.")),
            ("鸡肉", "jīròu", "chicken", ("白切鸡是广东名菜。", "Báiqiē jī shì Guǎngdōng míngcài.", "White-cut chicken is a famous Cantonese dish."), ("鸡肉比较健康。", "Jīròu bǐjiào jiànkāng.", "Chicken is relatively healthy.")),
            ("羊肉", "yángròu", "lamb", ("冬天吃羊肉火锅。", "Dōngtiān chī yángròu huǒguō.", "We eat lamb hot pot in winter."), ("羊肉要炖很久。", "Yángròu yào dùn hěn jiǔ.", "Lamb needs to be stewed a long time.")),
            ("排骨", "páigǔ", "pork ribs", ("红烧排骨很好吃。", "Hóngshāo páigǔ hěn hǎochī.", "Braised ribs are delicious."), ("请给我两斤排骨。", "Qǐng gěi wǒ liǎng jīn páigǔ.", "Please give me one kilo of ribs.")),
            ("香肠", "xiāngcháng", "sausage", ("早餐常吃香肠。", "Zǎocān cháng chī xiāngcháng.", "Sausage is often eaten for breakfast."), ("这种香肠很香。", "Zhè zhǒng xiāngcháng hěn xiāng.", "This sausage smells great.")),
            ("培根", "péigēn", "bacon", ("我喜欢培根鸡蛋。", "Wǒ xǐhuan péigēn jīdàn.", "I like bacon and eggs."), ("请给我三片培根。", "Qǐng gěi wǒ sān piàn péigēn.", "Please give me three slices of bacon.")),
            ("火腿", "huǒtuǐ", "ham", ("三明治里加了火腿。", "Sān míngzhì lǐ jiā le huǒtuǐ.", "Ham was added to the sandwich."), ("火腿切片很方便。", "Huǒtuǐ qiēpiàn hěn fāngbiàn.", "Sliced ham is convenient.")),
            ("牛排", "niúpái", "steak", ("我要五分熟牛排。", "Wǒ yào wǔ fēn shú niúpái.", "I'd like my steak medium."), ("这家牛排馆很有名。", "Zhè jiā niúpái guǎn hěn yǒumíng.", "This steakhouse is famous.")),
            ("烤鸭", "kǎoyā", "roast duck", ("北京烤鸭很有名。", "Běijīng kǎoyā hěn yǒumíng.", "Peking duck is famous."), ("我们点一只烤鸭。", "Wǒmen diǎn yī zhī kǎoyā.", "Let's order a roast duck.")),
        ],
        "seafood": [
            ("鱼", "yú", "fish", ("这条鱼很新鲜。", "Zhè tiáo yú hěn xīnxiān.", "This fish is very fresh."), ("我每周吃两次鱼。", "Wǒ měi zhōu chī liǎng cì yú.", "I eat fish twice a week.")),
            ("虾", "xiā", "shrimp", ("白灼虾很简单。", "Báizhuó xiā hěn jiǎndān.", "Boiled shrimp is simple."), ("这些虾很大。", "Zhèxiē xiā hěn dà.", "These shrimp are big.")),
            ("螃蟹", "pángxiè", "crab", ("秋天是吃螃蟹的季节。", "Qiūtiān shì chī pángxiè de jìjié.", "Autumn is crab season."), ("螃蟹要蒸十五分钟。", "Pángxiè yào zhēng shíwǔ fēnzhōng.", "Crabs need to steam for fifteen minutes.")),
            ("贝类", "bèilèi", "shellfish", ("贝类要煮透了再吃。", "Bèilèi yào zhǔ tòu le zài chī.", "Shellfish must be fully cooked."), ("我喜欢各种贝类。", "Wǒ xǐhuan gè zhǒng bèilèi.", "I like all kinds of shellfish.")),
            ("鱿鱼", "yóuyú", "squid", ("烤鱿鱼很香。", "Kǎo yóuyú hěn xiāng.", "Grilled squid smells great."), ("请给我一份炒鱿鱼。", "Qǐng gěi wǒ yī fèn chǎo yóuyú.", "Please give me stir-fried squid.")),
            ("三文鱼", "sānwényú", "salmon", ("三文鱼可以生吃。", "Sānwényú kěyǐ shēng chī.", "Salmon can be eaten raw."), ("我点一份三文鱼刺身。", "Wǒ diǎn yī fèn sānwényú cìshēn.", "I'll order salmon sashimi.")),
            ("生蚝", "shēng háo", "oyster", ("生蚝要配柠檬汁。", "Shēng háo yào pèi níngméng zhī.", "Oysters go well with lemon juice."), ("我不习惯吃生蚝。", "Wǒ bù xíguàn chī shēng háo.", "I'm not used to eating oysters.")),
            ("海带", "hǎidài", "kelp", ("海带汤很清爽。", "Hǎidài tāng hěn qīngshuǎng.", "Kelp soup is light and refreshing."), ("沙拉里加了海带丝。", "Shālā lǐ jiā le hǎidài sī.", "Shredded kelp was added to the salad.")),
            ("带鱼", "dàiyú", "hairtail fish", ("红烧带鱼是家常菜。", "Hóngshāo dàiyú shì jiācháng cài.", "Braised hairtail is a home-style dish."), ("带鱼要煎到两面金黄。", "Dàiyú yào jiān dào liǎngmiàn jīnhuáng.", "Hairtail should be fried golden on both sides.")),
            ("龙虾", "lóngxiā", "lobster", ("龙虾价格比较贵。", "Lóngxiā jiàgé bǐjiào guì.", "Lobster is relatively expensive."), ("我们庆祝时吃龙虾。", "Wǒmen qìngzhù shí chī lóngxiā.", "We eat lobster when celebrating.")),
        ],
        "cuisine": [
            ("米饭", "mǐfàn", "rice", ("请给我一碗米饭。", "Qǐng gěi wǒ yī wǎn mǐfàn.", "Please give me a bowl of rice."), ("米饭是主食。", "Mǐfàn shì zhǔshí.", "Rice is the staple food.")),
            ("面条", "miàntiáo", "noodles", ("这碗面条很劲道。", "Zhè wǎn miàntiáo hěn jìndào.", "These noodles are very chewy."), ("我喜欢吃汤面。", "Wǒ xǐhuan chī tāngmiàn.", "I like noodle soup.")),
            ("饺子", "jiǎozi", "dumplings", ("春节要吃饺子。", "Chūnjié yào chī jiǎozi.", "You eat dumplings during Spring Festival."), ("我包了一盘饺子。", "Wǒ bāo le yī pán jiǎozi.", "I made a plate of dumplings.")),
            ("包子", "bāozi", "steamed bun", ("早餐买了两个包子。", "Zǎocān mǎi le liǎng gè bāozi.", "I bought two buns for breakfast."), ("肉包子很香。", "Ròu bāozi hěn xiāng.", "Meat buns smell wonderful.")),
            ("火锅", "huǒguō", "hot pot", ("冬天最适合吃火锅。", "Dōngtiān zuì shìhé chī huǒguō.", "Hot pot is perfect for winter."), ("我们今晚去吃火锅。", "Wǒmen jīn wǎn qù chī huǒguō.", "We're having hot pot tonight.")),
            ("炒饭", "chǎofàn", "fried rice", ("扬州炒饭很有名。", "Yángzhōu chǎofàn hěn yǒumíng.", "Yangzhou fried rice is famous."), ("请给我一份蛋炒饭。", "Qǐng gěi wǒ yī fèn dàn chǎofàn.", "Please give me egg fried rice.")),
            ("汤", "tāng", "soup", ("这汤有点烫。", "Zhè tāng yǒudiǎn tàng.", "This soup is a bit hot."), ("饭前先喝碗汤。", "Fàn qián xiān hē wǎn tāng.", "Have a bowl of soup before the meal.")),
            ("炒菜", "chǎocài", "stir-fry", ("妈妈很会炒菜。", "Māma hěn huì chǎocài.", "Mom is great at stir-frying."), ("请再炒一个菜。", "Qǐng zài chǎo yī gè cài.", "Please stir-fry one more dish.")),
            ("小吃", "xiǎochī", "snack", ("这条街有很多小吃。", "Zhè tiáo jiē yǒu hěn duō xiǎochī.", "This street has many snacks."), ("小吃便宜又好吃。", "Xiǎochī piányi yòu hǎochī.", "Snacks are cheap and tasty.")),
            ("特色菜", "tèsè cài", "specialty dish", ("请推荐一道特色菜。", "Qǐng tuījiàn yī dào tèsè cài.", "Please recommend a specialty dish."), ("这是本店的特色菜。", "Zhè shì běn diàn de tèsè cài.", "This is our restaurant's signature dish.")),
        ],
        "street_food": [
            ("煎饼果子", "jiānbing guǒzi", "Chinese crepe wrap", ("早餐常吃煎饼果子。", "Zǎocān cháng chī jiānbing guǒzi.", "Jianbing is a common breakfast."), ("这个煎饼果子加蛋。", "Zhège jiānbing guǒzi jiā dàn.", "This jianbing has an egg added.")),
            ("烤串", "kǎochuàn", "grilled skewers", ("夜市有很多烤串。", "Yèshì yǒu hěn duō kǎochuàn.", "Night markets have lots of skewers."), ("请给我五串烤串。", "Qǐng gěi wǒ wǔ chuàn kǎochuàn.", "Please give me five skewers.")),
            ("麻辣烫", "málàtàng", "spicy hot pot soup", ("麻辣烫可以自己选菜。", "Málàtàng kěyǐ zìjǐ xuǎn cài.", "You pick your own ingredients for malatang."), ("这碗麻辣烫很辣。", "Zhè wǎn málàtàng hěn là.", "This malatang is very spicy.")),
            ("肉夹馍", "ròu jiā mó", "Chinese meat sandwich", ("肉夹馍是陕西名吃。", "Ròu jiā mó shì Shǎnxī míng chī.", "Roujiamo is a famous Shaanxi snack."), ("我买了一个肉夹馍。", "Wǒ mǎi le yī gè ròu jiā mó.", "I bought a roujiamo.")),
            ("臭豆腐", "chòu dòufu", "stinky tofu", ("臭豆腐闻着臭吃着香。", "Chòu dòufu wén zhe chòu chī zhe xiāng.", "Stinky tofu smells strong but tastes good."), ("你敢吃臭豆腐吗？", "Nǐ gǎn chī chòu dòufu ma?", "Do you dare to eat stinky tofu?")),
            ("糖葫芦", "tánghúlu", "candied hawthorn skewers", ("冬天常见糖葫芦。", "Dōngtiān chángjiàn tánghúlu.", "Candied hawthorn is common in winter."), ("孩子想要一串糖葫芦。", "Háizi xiǎng yào yī chuàn tánghúlu.", "The child wants a tanghulu skewer.")),
            ("肠粉", "chángfěn", "rice noodle roll", ("广东早餐常吃肠粉。", "Guǎngdōng zǎocān cháng chī chángfěn.", "Cheung fun is a common Guangdong breakfast."), ("请给我一份鸡蛋肠粉。", "Qǐng gěi wǒ yī fèn jīdàn chángfěn.", "Please give me egg cheung fun.")),
            ("小笼包", "xiǎolóngbāo", "soup dumplings", ("小笼包要小心烫。", "Xiǎolóngbāo yào xiǎoxīn tàng.", "Be careful, soup dumplings are hot."), ("上海小笼包很有名。", "Shànghǎi xiǎolóngbāo hěn yǒumíng.", "Shanghai soup dumplings are famous.")),
            ("凉皮", "liángpí", "cold skin noodles", ("夏天吃凉皮很解暑。", "Xiàtiān chī liángpí hěn jiěshǔ.", "Cold skin noodles are refreshing in summer."), ("请加醋和辣椒油。", "Qǐng jiā cù hé làjiāo yóu.", "Please add vinegar and chili oil.")),
            ("炸酱面", "zhájiàngmiàn", "noodles with soybean paste", ("炸酱面是北京特色。", "Zhájiàngmiàn shì Běijīng tèsè.", "Zhajiangmian is a Beijing specialty."), ("这碗炸酱面很地道。", "Zhè wǎn zhájiàngmiàn hěn dìdào.", "This zhajiangmian is authentic.")),
        ],
        "desserts": [
            ("蛋糕", "dàngāo", "cake", ("生日快乐，吃蛋糕吧。", "Shēngrì kuàilè, chī dàngāo ba.", "Happy birthday, let's eat cake."), ("这个蛋糕是巧克力味的。", "Zhège dàngāo shì qiǎokèlì wèi de.", "This cake is chocolate flavored.")),
            ("冰淇淋", "bīngqílín", "ice cream", ("夏天我最爱冰淇淋。", "Xiàtiān wǒ zuì ài bīngqílín.", "Ice cream is my favorite in summer."), ("请给我两个冰淇淋。", "Qǐng gěi wǒ liǎng gè bīngqílín.", "Please give me two ice creams.")),
            ("布丁", "bùdīng", "pudding", ("芒果布丁很滑。", "Mángguǒ bùdīng hěn huá.", "Mango pudding is smooth."), ("饭后甜点选了布丁。", "Fàn hòu tiándiǎn xuǎn le bùdīng.", "I chose pudding for dessert.")),
            ("月饼", "yuèbǐng", "mooncake", ("中秋节要吃月饼。", "Zhōngqiū jié yào chī yuèbǐng.", "You eat mooncakes during Mid-Autumn Festival."), ("这种月饼是五仁的。", "Zhè zhǒng yuèbǐng shì wǔrén de.", "This mooncake has mixed nuts filling.")),
            ("汤圆", "tāngyuán", "tangyuan", ("元宵节吃汤圆。", "Yuánxiāo jié chī tāngyuán.", "Tangyuan are eaten during Lantern Festival."), ("汤圆是甜的。", "Tāngyuán shì tián de.", "Tangyuan are sweet.")),
            ("红豆沙", "hóngdòushā", "red bean paste", ("包子馅是红豆沙。", "Bāozi xiàn shì hóngdòushā.", "The bun filling is red bean paste."), ("我喜欢红豆沙甜品。", "Wǒ xǐhuan hóngdòushā tiánpǐn.", "I like red bean desserts.")),
            ("马蹄糕", "mátí gāo", "water chestnut cake", ("马蹄糕是广式点心。", "Mátí gāo shì Guǎngshì diǎnxīn.", "Water chestnut cake is Cantonese dim sum."), ("这种糕点很清爽。", "Zhè zhǒng gāodiǎn hěn qīngshuǎng.", "This pastry is light and refreshing.")),
            ("蛋挞", "dàntà", "egg tart", ("新鲜出炉的蛋挞最好吃。", "Xīnxiān chūlú de dàntà zuì hǎochī.", "Freshly baked egg tarts are the best."), ("请给我三个蛋挞。", "Qǐng gěi wǒ sān gè dàntà.", "Please give me three egg tarts.")),
            ("双皮奶", "shuāngpí nǎi", "double-skin milk pudding", ("双皮奶是顺德名点。", "Shuāngpí nǎi shì Shùndé míng diǎn.", "Double-skin milk is a Shunde specialty."), ("这碗双皮奶很嫩。", "Zhè wǎn shuāngpí nǎi hěn nèn.", "This double-skin milk is very silky.")),
            ("麻花", "máhuā", "fried dough twist", ("麻花又脆又香。", "Máhuā yòu cuì yòu xiāng.", "Mahua is crispy and fragrant."), ("我买了一些麻花当零食。", "Wǒ mǎi le yīxiē máhuā dāng língshí.", "I bought some mahua as a snack.")),
        ],
        "coffee": [
            ("咖啡", "kāfēi", "coffee", ("我每天早上喝咖啡。", "Wǒ měitiān zǎoshang hē kāfēi.", "I drink coffee every morning."), ("请给我一杯热咖啡。", "Qǐng gěi wǒ yī bēi rè kāfēi.", "Please give me a hot coffee.")),
            ("拿铁", "nátiě", "latte", ("我要一杯冰拿铁。", "Wǒ yào yī bēi bīng nátiě.", "I'd like an iced latte."), ("拿铁奶泡很细腻。", "Nátiě nǎipào hěn xìnì.", "The latte foam is very fine.")),
            ("美式", "Měishì", "Americano", ("美式咖啡比较苦。", "Měishì kāfēi bǐjiào kǔ.", "Americano is rather bitter."), ("请换大杯美式。", "Qǐng huàn dà bēi Měishì.", "Please upgrade to a large Americano.")),
            ("卡布奇诺", "kǎbùqínuò", "cappuccino", ("卡布奇诺上面是奶泡。", "Kǎbùqínuò shàngmiàn shì nǎipào.", "Cappuccino has foam on top."), ("她点了卡布奇诺。", "Tā diǎn le kǎbùqínuò.", "She ordered a cappuccino.")),
            ("浓缩", "nóngsuō", "espresso", ("浓缩咖啡很小杯。", "Nóngsuō kāfēi hěn xiǎo bēi.", "Espresso comes in a small cup."), ("请做双份浓缩。", "Qǐng zuò shuāng fèn nóngsuō.", "Please make a double espresso.")),
            ("咖啡豆", "kāfēidòu", "coffee beans", ("这些咖啡豆很新鲜。", "Zhèxiē kāfēidòu hěn xīnxiān.", "These coffee beans are fresh."), ("我买了埃塞俄比亚咖啡豆。", "Wǒ mǎi le Āisāi'ébǐyà kāfēidòu.", "I bought Ethiopian coffee beans.")),
            ("研磨", "yánmó", "to grind coffee", ("请帮我研磨咖啡豆。", "Qǐng bāng wǒ yánmó kāfēidòu.", "Please grind the coffee beans for me."), ("现磨咖啡更香。", "Xiàn mó kāfēi gèng xiāng.", "Freshly ground coffee smells better.")),
            ("外带", "wàidài", "to go", ("咖啡外带还是堂食？", "Kāfēi wàidài háishi tángshí?", "Coffee to go or for here?"), ("我要外带。", "Wǒ yào wàidài.", "I'll take it to go.")),
            ("半糖", "bàntáng", "half sugar", ("请做半糖。", "Qǐng zuò bàntáng.", "Please make it half sugar."), ("半糖对我来说刚好。", "Bàntáng duì wǒ lái shuō gānghǎo.", "Half sugar is just right for me.")),
            ("拉花", "lāhuā", "latte art", ("这杯咖啡拉花很漂亮。", "Zhè bēi kāfēi lāhuā hěn piàoliang.", "The latte art on this coffee is beautiful."), ("店员擅长拉花。", "Diànyuán shàncháng lāhuā.", "The barista is good at latte art.")),
        ],
        "tea": [
            ("绿茶", "lǜchá", "green tea", ("绿茶比较清淡。", "Lǜchá bǐjiào qīngdàn.", "Green tea is relatively light."), ("请泡一杯绿茶。", "Qǐng pào yī bēi lǜchá.", "Please brew a cup of green tea.")),
            ("红茶", "hóngchá", "black tea", ("红茶适合加牛奶。", "Hóngchá shìhé jiā niúnǎi.", "Black tea goes well with milk."), ("英式红茶很浓。", "Yīngshì hóngchá hěn nóng.", "English black tea is strong.")),
            ("乌龙茶", "wūlóngchá", "oolong tea", ("乌龙茶可以反复冲泡。", "Wūlóngchá kěyǐ fǎnfù chōngpào.", "Oolong can be steeped multiple times."), ("铁观音是乌龙茶。", "Tiěguānyīn shì wūlóngchá.", "Tieguanyin is an oolong tea.")),
            ("茉莉花茶", "mòlì huāchá", "jasmine tea", ("茉莉花茶很香。", "Mòlì huāchá hěn xiāng.", "Jasmine tea is very fragrant."), ("饭后我喝茉莉花茶。", "Fàn hòu wǒ hē mòlì huāchá.", "I drink jasmine tea after meals.")),
            ("普洱茶", "pǔ'ěrchá", "Pu'er tea", ("普洱茶可以收藏。", "Pǔ'ěrchá kěyǐ shōucáng.", "Pu'er tea can be aged and collected."), ("熟普洱口感醇厚。", "Shú pǔ'ěr kǒugǎn chúnhòu.", "Ripe Pu'er has a rich flavor.")),
            ("泡茶", "pào chá", "to brew tea", ("我来泡茶。", "Wǒ lái pào chá.", "Let me brew the tea."), ("水温太高不适合泡茶。", "Shuǐwēn tài gāo bú shìhé pào chá.", "Water that's too hot isn't good for brewing tea.")),
            ("茶叶", "cháyè", "tea leaves", ("这些茶叶是今年的新茶。", "Zhèxiē cháyè shì jīnnián de xīnchá.", "These tea leaves are this year's new harvest."), ("茶叶要密封保存。", "Cháyè yào mìfēng bǎocún.", "Tea leaves should be stored sealed.")),
            ("功夫茶", "gōngfuchá", "gongfu tea ceremony", ("广东人喜欢喝功夫茶。", "Guǎngdōng rén xǐhuan hē gōngfuchá.", "People in Guangdong enjoy gongfu tea."), ("功夫茶讲究水温。", "Gōngfuchá jiǎngjiū shuǐwēn.", "Gongfu tea emphasizes water temperature.")),
            ("茶馆", "cháguǎn", "teahouse", ("我们去茶馆坐坐。", "Wǒmen qù cháguǎn zuòzuò.", "Let's sit at a teahouse."), ("这家茶馆环境很好。", "Zhè jiā cháguǎn huánjìng hěn hǎo.", "This teahouse has a nice atmosphere.")),
            ("倒茶", "dào chá", "to pour tea", ("请帮我倒茶。", "Qǐng bāng wǒ dào chá.", "Please pour me some tea."), ("倒茶时先给长辈。", "Dào chá shí xiān gěi zhǎngbèi.", "Serve tea to elders first.")),
        ],
        "drinks": [
            ("水", "shuǐ", "water", ("请给我一杯水。", "Qǐng gěi wǒ yī bēi shuǐ.", "Please give me a glass of water."), ("多喝水对身体好。", "Duō hē shuǐ duì shēntǐ hǎo.", "Drinking more water is good for you.")),
            ("果汁", "guǒzhī", "fruit juice", ("鲜榨果汁没有添加剂。", "Xiānzhà guǒzhī méiyǒu tiānjiājì.", "Fresh juice has no additives."), ("孩子喜欢喝橙汁。", "Háizi xǐhuan hē chéngzhī.", "Kids like drinking orange juice.")),
            ("牛奶", "niúnǎi", "milk", ("我早餐喝牛奶。", "Wǒ zǎocān hē niúnǎi.", "I drink milk for breakfast."), ("这盒牛奶要冷藏。", "Zhè hé niúnǎi yào lěngcáng.", "This milk needs refrigeration.")),
            ("可乐", "kělè", "cola", ("请给我一罐可乐。", "Qǐng gěi wǒ yī guàn kělè.", "Please give me a can of cola."), ("少喝可乐比较好。", "Shǎo hē kělè bǐjiào hǎo.", "It's better to drink less cola.")),
            ("啤酒", "píjiǔ", "beer", ("夏天喝冰啤酒很爽。", "Xiàtiān hē bīng píjiǔ hěn shuǎng.", "Ice cold beer is great in summer."), ("请给我两瓶啤酒。", "Qǐng gěi wǒ liǎng píng píjiǔ.", "Please give me two bottles of beer.")),
            ("白酒", "báijiǔ", "baijiu", ("白酒度数很高。", "Báijiǔ dùshù hěn gāo.", "Baijiu has a high alcohol content."), ("宴席上常喝白酒。", "Yànxí shàng cháng hē báijiǔ.", "Baijiu is often served at banquets.")),
            ("红酒", "hóngjiǔ", "red wine", ("红酒要醒一下。", "Hóngjiǔ yào xǐng yīxià.", "Red wine needs to breathe."), ("我们庆祝时开了一瓶红酒。", "Wǒmen qìngzhù shí kāi le yī píng hóngjiǔ.", "We opened a bottle of red wine to celebrate.")),
            ("豆浆", "dòujiāng", "soy milk", ("早餐配油条和豆浆。", "Zǎocān pèi yóutiáo hé dòujiāng.", "Breakfast with youtiao and soy milk."), ("热豆浆很好喝。", "Rè dòujiāng hěn hǎo hē.", "Hot soy milk is delicious.")),
            ("奶茶", "nǎichá", "milk tea", ("珍珠奶茶很流行。", "Zhēnzhū nǎichá hěn liúxíng.", "Bubble milk tea is very popular."), ("我要一杯少糖奶茶。", "Wǒ yào yī bēi shǎo táng nǎichá.", "I'd like a milk tea with less sugar.")),
            ("功能饮料", "gōngnéng yǐnliào", "energy drink", ("运动后喝功能饮料。", "Yùndòng hòu hē gōngnéng yǐnliào.", "Drink an energy drink after exercise."), ("功能饮料不要多喝。", "Gōngnéng yǐnliào bú yào duō hē.", "Don't drink too many energy drinks.")),
        ],
    }
    return _flatten_sections(data)


def build_culture() -> list[dict]:
    from study_vocab_culture_tech import CULTURE
    return _flatten_sections(CULTURE)


def build_technology() -> list[dict]:
    from study_vocab_culture_tech import TECHNOLOGY
    return _flatten_sections(TECHNOLOGY)


def write_json(filename: str, words: list[dict]) -> None:
    path = DATA_DIR / filename
    with path.open("w", encoding="utf-8") as f:
        json.dump(words, f, ensure_ascii=False, indent=2)
        f.write("\n")


def print_counts(filename: str, words: list[dict]) -> None:
    counts = Counter(w["section"] for w in words)
    print(f"\n{filename} ({len(words)} words total):")
    for section, count in counts.items():
        print(f"  {section}: {count}")


def main() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    existing_travel = load_existing_travel()

    generators = {
        "travel.json": build_travel(existing_travel),
        "business.json": build_business(),
        "daily_life.json": build_daily_life(),
        "food.json": build_food(),
        "culture.json": build_culture(),
        "technology.json": build_technology(),
    }

    for filename, words in generators.items():
        write_json(filename, words)
        print_counts(filename, words)

    print("\nDone. Generated 6 study set files in", DATA_DIR)


if __name__ == "__main__":
    main()
