"""Culture and technology vocabulary for generate_study_sets.py."""

CULTURE = {
    "cny": [
        ("春节", "Chūnjié", "Spring Festival / Chinese New Year", ("春节是中国人最重要的节日。", "Chūnjié shì Zhōngguó rén zuì zhòngyào de jiérì.", "Spring Festival is the most important Chinese holiday."), ("我们回老家过春节。", "Wǒmen huí lǎojiā guò Chūnjié.", "We go home to celebrate Spring Festival.")),
        ("红包", "hóngbāo", "red envelope", ("长辈给孩子发红包。", "Zhǎngbèi gěi háizi fā hóngbāo.", "Elders give red envelopes to children."), ("谢谢你的红包。", "Xièxie nǐ de hóngbāo.", "Thank you for the red envelope.")),
        ("年夜饭", "niányèfàn", "New Year's Eve dinner", ("全家人一起吃年夜饭。", "Quán jiārén yīqǐ chī niányèfàn.", "The whole family eats New Year's Eve dinner together."), ("年夜饭很丰盛。", "Niányèfàn hěn fēngshèng.", "The reunion dinner is lavish.")),
        ("春联", "chūnlián", "Spring Festival couplets", ("门口贴上了春联。", "Ménkǒu tiē shàng le chūnlián.", "Spring couplets were pasted on the door."), ("这幅春联写得很工整。", "Zhè fú chūnlián xiě de hěn gōngzhěng.", "This couplet is written very neatly.")),
        ("烟花", "yānhuā", "fireworks", ("除夕夜看烟花。", "Chúxī yè kàn yānhuā.", "Watch fireworks on New Year's Eve."), ("城市禁止燃放烟花。", "Chéngshì jìnzhǐ ránfàng yānhuā.", "The city bans fireworks.")),
        ("拜年", "bàinián", "to pay New Year visits", ("大年初一去拜年。", "Dànián chūyī qù bàinián.", "Visit relatives on the first day of the new year."), ("我给你拜年了。", "Wǒ gěi nǐ bàinián le.", "I'm paying you a New Year visit.")),
        ("灯笼", "dēnglong", "lantern", ("街上挂满了红灯笼。", "Jiē shàng guà mǎn le hóng dēnglong.", "Red lanterns hang all over the street."), ("这个灯笼很漂亮。", "Zhège dēnglong hěn piàoliang.", "This lantern is beautiful.")),
        ("舞龙", "wǔ lóng", "dragon dance", ("春节有舞龙表演。", "Chūnjié yǒu wǔ lóng biǎoyǎn.", "There are dragon dances during Spring Festival."), ("舞龙队伍很壮观。", "Wǔ lóng duìwu hěn zhuàngguān.", "The dragon dance troupe is spectacular.")),
        ("团圆", "tuányuán", "reunion", ("春节是团圆的日子。", "Chūnjié shì tuányuán de rìzi.", "Spring Festival is a time for reunion."), ("一家人团圆最重要。", "Yī jiā rén tuányuán zuì zhòngyào.", "Family reunion matters most.")),
        ("守岁", "shǒusuì", "to stay up on New Year's Eve", ("我们除夕守岁。", "Wǒmen chúxī shǒusuì.", "We stay up on New Year's Eve."), ("守岁到半夜。", "Shǒusuì dào bànyè.", "Stay up until midnight.")),
    ],
    "dragon_boat": [
        ("端午节", "Duānwǔ Jié", "Dragon Boat Festival", ("端午节在农历五月初五。", "Duānwǔ Jié zài nónglì wǔ yuè chū wǔ.", "Dragon Boat Festival is on the fifth day of the fifth lunar month."), ("端午节吃粽子。", "Duānwǔ Jié chī zòngzi.", "People eat zongzi during Dragon Boat Festival.")),
        ("粽子", "zòngzi", "sticky rice dumpling", ("我喜欢肉粽子。", "Wǒ xǐhuan ròu zòngzi.", "I like savory zongzi."), ("妈妈包了一锅粽子。", "Māma bāo le yī guō zòngzi.", "Mom made a pot of zongzi.")),
        ("龙舟", "lóngzhōu", "dragon boat", ("龙舟比赛很激烈。", "Lóngzhōu bǐsài hěn jīliè.", "Dragon boat racing is intense."), ("他们队龙舟划得很快。", "Tāmen duì lóngzhōu huá de hěn kuài.", "Their team paddles very fast.")),
        ("屈原", "Qū Yuán", "Qu Yuan", ("端午节纪念屈原。", "Duānwǔ Jié jìniàn Qū Yuán.", "Dragon Boat Festival commemorates Qu Yuan."), ("屈原是伟大的诗人。", "Qū Yuán shì wěidà de shīrén.", "Qu Yuan was a great poet.")),
        ("艾草", "àicǎo", "mugwort", ("门口挂艾草驱邪。", "Ménkǒu guà àicǎo qū xié.", "Mugwort is hung at the door to ward off evil."), ("艾草有特殊香味。", "Àicǎo yǒu tèshū xiāngwèi.", "Mugwort has a distinct scent.")),
        ("香囊", "xiāngnáng", "sachet / scented pouch", ("孩子佩戴香囊。", "Háizi pèidài xiāngnáng.", "Children wear scented sachets."), ("这个香囊是手工做的。", "Zhège xiāngnáng shì shǒugōng zuò de.", "This sachet is handmade.")),
        ("赛龙舟", "sài lóngzhōu", "dragon boat race", ("明天有赛龙舟。", "Míngtiān yǒu sài lóngzhōu.", "There's a dragon boat race tomorrow."), ("赛龙舟是传统活动。", "Sài lóngzhōu shì chuántǒng huódòng.", "Dragon boat racing is a traditional activity.")),
        ("雄黄酒", "xiónghuángjiǔ", "realgar wine", ("端午喝雄黄酒是习俗。", "Duānwǔ hē xiónghuángjiǔ shì xísú.", "Drinking realgar wine is a Dragon Boat custom."), ("现在很少喝雄黄酒了。", "Xiànzài hěn shǎo hē xiónghuángjiǔ le.", "Realgar wine is rarely consumed now.")),
        ("五彩绳", "wǔcǎi shéng", "colorful braided cord", ("给孩子系五彩绳。", "Gěi háizi jì wǔcǎi shéng.", "Tie colorful cords on children."), ("五彩绳寓意平安。", "Wǔcǎi shéng yùyì píng'ān.", "Colorful cords symbolize safety.")),
        ("划桨", "huájiǎng", "to paddle", ("队员整齐地划桨。", "Duìyuán zhěngqí de huájiǎng.", "Team members paddle in unison."), ("划桨需要很大力气。", "Huájiǎng xūyào hěn dà lìqi.", "Paddling takes a lot of strength.")),
    ],
    "lantern": [
        ("元宵节", "Yuánxiāo Jié", "Lantern Festival", ("元宵节是春节的最后一天。", "Yuánxiāo Jié shì Chūnjié de zuìhòu yī tiān.", "Lantern Festival is the last day of Spring Festival."), ("元宵节看花灯。", "Yuánxiāo Jié kàn huādēng.", "People view lanterns on Lantern Festival.")),
        ("花灯", "huādēng", "decorative lantern", ("公园里有各种花灯。", "Gōngyuán lǐ yǒu gè zhǒng huādēng.", "There are all kinds of lanterns in the park."), ("这个花灯是兔子的形状。", "Zhège huādēng shì tùzi de xíngzhuàng.", "This lantern is shaped like a rabbit.")),
        ("猜灯谜", "cāi dēngmí", "to guess lantern riddles", ("我们在灯会上猜灯谜。", "Wǒmen zài dēnghuì shàng cāi dēngmí.", "We guess lantern riddles at the fair."), ("这个灯谜很难。", "Zhège dēngmí hěn nán.", "This lantern riddle is hard.")),
        ("汤圆", "tāngyuán", "tangyuan", ("元宵节吃汤圆。", "Yuánxiāo Jié chī tāngyuán.", "Eat tangyuan on Lantern Festival."), ("芝麻汤圆很好吃。", "Zhīma tāngyuán hěn hǎochī.", "Sesame tangyuan is delicious.")),
        ("灯会", "dēnghuì", "lantern fair", ("灯会很热闹。", "Dēnghuì hěn rènao.", "The lantern fair is lively."), ("我们全家去逛灯会。", "Wǒmen quán jiā qù guàng dēnghuì.", "Our whole family goes to the lantern fair.")),
        ("走马灯", "zǒumǎdēng", "revolving lantern", ("走马灯里的图案会动。", "Zǒumǎdēng lǐ de tú'àn huì dòng.", "The pictures inside a revolving lantern move."), ("这种走马灯很精巧。", "Zhè zhǒng zǒumǎdēng hěn jīngqiǎo.", "This type of revolving lantern is intricate.")),
        ("孔明灯", "kǒngmíng dēng", "sky lantern", ("人们放孔明灯许愿。", "Rénmen fàng kǒngmíng dēng xǔyuàn.", "People release sky lanterns to make wishes."), ("孔明灯慢慢升上天空。", "Kǒngmíng dēng mànmàn shēng shàng tiānkōng.", "Sky lanterns slowly rise into the sky.")),
        ("赏月", "shǎng yuè", "to admire the moon", ("元宵夜一起赏月。", "Yuánxiāo yè yīqǐ shǎng yuè.", "Admire the moon together on Lantern Festival night."), ("我们在阳台赏月。", "Wǒmen zài yángtái shǎng yuè.", "We admire the moon from the balcony.")),
        ("团圆", "tuányuán", "reunion", ("元宵节也是团圆节。", "Yuánxiāo Jié yě shì tuányuán jié.", "Lantern Festival is also a reunion festival."), ("元宵节家人要团圆。", "Yuánxiāo Jié jiārén yào tuányuán.", "Families reunite on Lantern Festival.")),
        ("烟花", "yānhuā", "fireworks", ("元宵夜有烟花表演。", "Yuánxiāo yè yǒu yānhuā biǎoyǎn.", "There's a fireworks show on Lantern Festival night."), ("孩子们喜欢看烟花。", "Háizimen xǐhuan kàn yānhuā.", "Children love watching fireworks.")),
    ],
    "mid_autumn": [
        ("中秋节", "Zhōngqiū Jié", "Mid-Autumn Festival", ("中秋节在农历八月十五。", "Zhōngqiū Jié zài nónglì bā yuè shíwǔ.", "Mid-Autumn Festival is on the 15th of the eighth lunar month."), ("中秋节家人团聚。", "Zhōngqiū Jié jiārén tuánjù.", "Families gather on Mid-Autumn Festival.")),
        ("月饼", "yuèbǐng", "mooncake", ("中秋节吃月饼。", "Zhōngqiū Jié chī yuèbǐng.", "Eat mooncakes on Mid-Autumn Festival."), ("莲蓉月饼很受欢迎。", "Liánróng yuèbǐng hěn shòu huānyíng.", "Lotus seed mooncakes are popular.")),
        ("赏月", "shǎng yuè", "to admire the full moon", ("中秋夜赏月。", "Zhōngqiū yè shǎng yuè.", "Admire the moon on Mid-Autumn night."), ("今晚的月亮又圆又亮。", "Jīn wǎn de yuèliang yòu yuán yòu liàng.", "Tonight's moon is round and bright.")),
        ("嫦娥", "Cháng'é", "Chang'e (moon goddess)", ("嫦娥奔月是中秋传说。", "Cháng'é bēn yuè shì Zhōngqiū chuánshuō.", "Chang'e flying to the moon is a Mid-Autumn legend."), ("孩子们听嫦娥的故事。", "Háizimen tīng Cháng'é de gùshi.", "Children hear the story of Chang'e.")),
        ("玉兔", "yùtù", "Jade Rabbit", ("玉兔在月宫里。", "Yùtù zài yuègōng lǐ.", "The Jade Rabbit lives in the moon palace."), ("月饼上常印玉兔图案。", "Yuèbǐng shàng cháng yìn yùtù tú'àn.", "Mooncakes often bear the Jade Rabbit design.")),
        ("团圆", "tuányuán", "reunion", ("中秋是团圆的日子。", "Zhōngqiū shì tuányuán de rìzi.", "Mid-Autumn is a day for reunion."), ("不能回家也要视频团圆。", "Bù néng huí jiā yě yào shìpín tuányuán.", "Even if you can't go home, reunite by video.")),
        ("桂花", "guìhuā", "osmanthus", ("中秋时节桂花很香。", "Zhōngqiū shíjié guìhuā hěn xiāng.", "Osmanthus blooms fragrantly at Mid-Autumn."), ("桂花糕是应季点心。", "Guìhuā gāo shì yìngjì diǎnxīn.", "Osmanthus cake is a seasonal treat.")),
        ("灯笼", "dēnglong", "lantern", ("中秋也挂灯笼。", "Zhōngqiū yě guà dēnglong.", "Lanterns are also hung at Mid-Autumn."), ("孩子提着灯笼玩。", "Háizi tí zhe dēnglong wán.", "Children play carrying lanterns.")),
        ("思念", "sīniàn", "to miss / longing", ("中秋让人思念家乡。", "Zhōngqiū ràng rén sīniàn jiāxiāng.", "Mid-Autumn makes people miss home."), ("我思念远方的亲人。", "Wǒ sīniàn yuǎnfāng de qīnrén.", "I miss my family far away.")),
        ("圆满", "yuánmǎn", "fulfillment / completeness", ("月亮象征圆满。", "Yuèliang xiàngzhēng yuánmǎn.", "The full moon symbolizes completeness."), ("祝大家中秋圆满。", "Zhù dàjiā Zhōngqiū yuánmǎn.", "Wishing everyone a fulfilling Mid-Autumn.")),
    ],
    "pandas": [
        ("熊猫", "xióngmāo", "panda", ("熊猫是中国的国宝。", "Xióngmāo shì Zhōngguó de guóbǎo.", "Pandas are China's national treasure."), ("孩子们喜欢看熊猫。", "Háizimen xǐhuan kàn xióngmāo.", "Children love watching pandas.")),
        ("竹子", "zhúzi", "bamboo", ("熊猫主要吃竹子。", "Xióngmāo zhǔyào chī zhúzi.", "Pandas mainly eat bamboo."), ("这片竹林很茂密。", "Zhè piàn zhúlín hěn màomì.", "This bamboo grove is dense.")),
        ("成都", "Chéngdū", "Chengdu", ("成都是看熊猫的好地方。", "Chéngdū shì kàn xióngmāo de hǎo dìfang.", "Chengdu is a great place to see pandas."), ("成都大熊猫基地很有名。", "Chéngdū dà xióngmāo jīdì hěn yǒumíng.", "Chengdu Panda Base is famous.")),
        ("基地", "jīdì", "base / reserve", ("基地里有很多熊猫。", "Jīdì lǐ yǒu hěn duō xióngmāo.", "There are many pandas at the base."), ("保护基地禁止喧哗。", "Bǎohù jīdì jìnzhǐ xuānhuá.", "Quiet is required at the conservation base.")),
        ("保育", "bǎoyù", "conservation / breeding", ("熊猫保育工作很重要。", "Xióngmāo bǎoyù gōngzuò hěn zhòngyào.", "Panda conservation is very important."), ("保育员照顾熊猫宝宝。", "Bǎoyùyuán zhàogù xióngmāo bǎobǎo.", "Keepers care for panda cubs.")),
        ("黑白", "hēibái", "black and white", ("熊猫是黑白色。", "Xióngmāo shì hēibái sè.", "Pandas are black and white."), ("黑白配色很可爱。", "Hēibái pèisè hěn kě'ài.", "The black-and-white coloring is adorable.")),
        ("憨态", "hāntài", "clumsy cute manner", ("熊猫的憨态可掬。", "Xióngmāo de hāntài kějū.", "Pandas have a lovable clumsy charm."), ("它憨态十足。", "Tā hāntài shízú.", "It's full of adorable clumsiness.")),
        ("爬树", "pá shù", "to climb trees", ("小熊猫在学爬树。", "Xiǎo xióngmāo zài xué pá shù.", "A young panda is learning to climb."), ("熊猫爬树很灵活。", "Xióngmāo pá shù hěn línghuó.", "Pandas climb trees nimbly.")),
        ("打滚", "dǎgǔn", "to roll around", ("熊猫在地上打滚。", "Xióngmāo zài dìshang dǎgǔn.", "The panda rolls on the ground."), ("它高兴时会打滚。", "Tā gāoxìng shí huì dǎgǔn.", "It rolls around when happy.")),
        ("濒危", "bīnwēi", "endangered", ("熊猫曾经濒危。", "Xióngmāo céngjīng bīnwēi.", "Pandas were once endangered."), ("保护濒危动物人人有责。", "Bǎohù bīnwēi dòngwù rénrén yǒu zé.", "Everyone has a duty to protect endangered animals.")),
    ],
    "tea_culture": [
        ("茶道", "chádào", "tea ceremony", ("日本茶道源于中国。", "Rìběn chádào yuán yú Zhōngguó.", "Japanese tea ceremony originated in China."), ("她学习中国传统茶道。", "Tā xuéxí Zhōngguó chuántǒng chádào.", "She studies traditional Chinese tea ceremony.")),
        ("茶艺", "cháyì", "tea art", ("茶艺表演很优雅。", "Cháyì biǎoyǎn hěn yōuyǎ.", "Tea art performances are elegant."), ("她精通茶艺。", "Tā jīngtōng cháyì.", "She is skilled in tea art.")),
        ("茶具", "chájù", "tea set / utensils", ("这套茶具是景德镇做的。", "Zhè tào chájù shì Jǐngdézhèn zuò de.", "This tea set is from Jingdezhen."), ("茶具要清洗干净。", "Chájù yào qīngxǐ gānjìng.", "Tea utensils must be cleaned well.")),
        ("敬茶", "jìng chá", "to serve tea respectfully", ("新人向长辈敬茶。", "Xīnrén xiàng zhǎngbèi jìng chá.", "Newlyweds serve tea to elders."), ("敬茶表示尊敬。", "Jìng chá biǎoshì zūnjìng.", "Serving tea shows respect.")),
        ("品茶", "pǐn chá", "to taste / appreciate tea", ("请慢慢品茶。", "Qǐng mànmàn pǐn chá.", "Please savor the tea slowly."), ("品茶需要静心。", "Pǐn chá xūyào jìngxīn.", "Tea tasting requires a calm mind.")),
        ("龙井", "Lóngjǐng", "Longjing tea", ("龙井是杭州名茶。", "Lóngjǐng shì Hángzhōu míng chá.", "Longjing is a famous Hangzhou tea."), ("明前龙井价格很高。", "Míng qián Lóngjǐng jiàgé hěn gāo.", "Pre-Qingming Longjing is very expensive.")),
        ("铁观音", "Tiěguānyīn", "Tieguanyin oolong", ("铁观音是福建名茶。", "Tiěguānyīn shì Fújiàn míng chá.", "Tieguanyin is a famous Fujian tea."), ("这泡铁观音回甘很好。", "Zhè pào Tiěguānyīn huígān hěn hǎo.", "This Tieguanyin has a nice sweet aftertaste.")),
        ("茶馆", "cháguǎn", "teahouse", ("老北京人爱去茶馆。", "Lǎo Běijīng rén ài qù cháguǎn.", "Old Beijingers love teahouses."), ("茶馆里可以听相声。", "Cháguǎn lǐ kěyǐ tīng xiàngsheng.", "You can hear cross-talk at teahouses.")),
        ("以茶会友", "yǐ chá huì yǒu", "to meet friends over tea", ("以茶会友是中国传统。", "Yǐ chá huì yǒu shì Zhōngguó chuántǒng.", "Meeting friends over tea is a Chinese tradition."), ("今天以茶会友，聊得很开心。", "Jīntiān yǐ chá huì yǒu, liáo de hěn kāixīn.", "We met over tea today and had a great chat.")),
        ("回甘", "huígān", "sweet aftertaste (tea)", ("好茶会有回甘。", "Hǎo chá huì yǒu huígān.", "Good tea has a sweet aftertaste."), ("这茶回甘持久。", "Zhè chá huígān chíjiǔ.", "This tea's aftertaste lingers.")),
    ],
    "landmarks": [
        ("长城", "Chángchéng", "Great Wall", ("长城是世界奇迹。", "Chángchéng shì shìjiè qíjì.", "The Great Wall is a world wonder."), ("我们去长城徒步。", "Wǒmen qù Chángchéng túbù.", "We hiked the Great Wall.")),
        ("故宫", "Gùgōng", "Forbidden City", ("故宫在北京中心。", "Gùgōng zài Běijīng zhōngxīn.", "The Forbidden City is in central Beijing."), ("故宫有六百多年历史。", "Gùgōng yǒu liùbǎi duō nián lìshǐ.", "The Forbidden City is over 600 years old.")),
        ("天安门", "Tiān'ānmén", "Tiananmen", ("天安门广场很大。", "Tiān'ānmén Guǎngchǎng hěn dà.", "Tiananmen Square is very large."), ("天安门是北京的象征。", "Tiān'ānmén shì Běijīng de xiàngzhēng.", "Tiananmen is a symbol of Beijing.")),
        ("西湖", "Xīhú", "West Lake", ("西湖风景如画。", "Xīhú fēngjǐng rú huà.", "West Lake scenery is picturesque."), ("我们在西湖边散步。", "Wǒmen zài Xīhú biān sànbù.", "We walked along West Lake.")),
        ("兵马俑", "Bīngmǎyǒng", "Terracotta Army", ("兵马俑在西安。", "Bīngmǎyǒng zài Xī'ān.", "The Terracotta Army is in Xi'an."), ("兵马俑非常壮观。", "Bīngmǎyǒng fēicháng zhuàngguān.", "The Terracotta Army is spectacular.")),
        ("黄山", "Huángshān", "Mount Huang", ("黄山以奇松怪石闻名。", "Huángshān yǐ qísōng guàishí wénmíng.", "Mount Huang is famous for odd pines and rocks."), ("我们登黄山看日出。", "Wǒmen dēng Huángshān kàn rìchū.", "We climbed Mount Huang to see the sunrise.")),
        ("桂林", "Guìlín", "Guilin", ("桂林山水甲天下。", "Guìlín shānshuǐ jiǎ tiānxià.", "Guilin's scenery is the finest under heaven."), ("我们去桂林游漓江。", "Wǒmen qù Guìlín yóu Líjiāng.", "We went to Guilin to cruise the Li River.")),
        ("布达拉宫", "Bùdálā Gōng", "Potala Palace", ("布达拉宫在拉萨。", "Bùdálā Gōng zài Lāsà.", "The Potala Palace is in Lhasa."), ("布达拉宫非常雄伟。", "Bùdálā Gōng fēicháng xióngwěi.", "The Potala Palace is magnificent.")),
        ("外滩", "Wàitān", "The Bund (Shanghai)", ("外滩夜景很美。", "Wàitān yèjǐng hěn měi.", "The Bund at night is beautiful."), ("我们去外滩看东方明珠。", "Wǒmen qù Wàitān kàn Dōngfāng Míngzhū.", "We went to the Bund to see Oriental Pearl Tower.")),
        ("苏州园林", "Sūzhōu yuánlín", "Suzhou gardens", ("苏州园林很精致。", "Sūzhōu yuánlín hěn jīngzhì.", "Suzhou gardens are exquisite."), ("拙政园是苏州名园。", "Zhuōzhèng Yuán shì Sūzhōu míng yuán.", "Humble Administrator's Garden is a famous Suzhou garden.")),
    ],
    "zodiac": [
        ("生肖", "shēngxiào", "Chinese zodiac sign", ("你的生肖是什么？", "Nǐ de shēngxiào shì shénme?", "What's your zodiac sign?"), ("生肖共有十二种。", "Shēngxiào gòng yǒu shí'èr zhǒng.", "There are twelve zodiac signs.")),
        ("鼠", "shǔ", "Rat (zodiac)", ("属鼠的人很聪明。", "Shǔ shǔ de rén hěn cōngming.", "People born in the Year of the Rat are clever."), ("鼠是第一个生肖。", "Shǔ shì dì yī gè shēngxiào.", "The Rat is the first zodiac sign.")),
        ("龙", "lóng", "Dragon (zodiac)", ("龙是中国最重要的生肖。", "Lóng shì Zhōngguó zuì zhòngyào de shēngxiào.", "The Dragon is the most important Chinese zodiac sign."), ("属龙的人很有活力。", "Shǔ lóng de rén hěn yǒu huólì.", "People born in the Year of the Dragon are energetic.")),
        ("虎", "hǔ", "Tiger (zodiac)", ("虎年出生的孩子很多。", "Hǔ nián chūshēng de háizi hěn duō.", "Many children are born in the Year of the Tiger."), ("属虎的人很勇敢。", "Shǔ hǔ de rén hěn yǒnggǎn.", "People born in the Year of the Tiger are brave.")),
        ("兔", "tù", "Rabbit (zodiac)", ("兔年人温和。", "Tù nián rén wēnhé.", "People born in the Year of the Rabbit are gentle."), ("属兔的今年运势不错。", "Shǔ tù de jīnnián yùnshì búcuò.", "Rabbit sign has good fortune this year.")),
        ("蛇", "shé", "Snake (zodiac)", ("属蛇的人很有智慧。", "Shǔ shé de rén hěn yǒu zhìhuì.", "People born in the Year of the Snake are wise."), ("蛇在生肖中排第六。", "Shé zài shēngxiào zhōng pái dì liù.", "The Snake ranks sixth in the zodiac.")),
        ("马", "mǎ", "Horse (zodiac)", ("属马的人喜欢自由。", "Shǔ mǎ de rén xǐhuan zìyóu.", "People born in the Year of the Horse love freedom."), ("马象征成功。", "Mǎ xiàngzhēng chénggōng.", "The Horse symbolizes success.")),
        ("羊", "yáng", "Goat (zodiac)", ("属羊的人很温柔。", "Shǔ yáng de rén hěn wēnróu.", "People born in the Year of the Goat are gentle."), ("羊年出生的人不少。", "Yáng nián chūshēng de rén bù shǎo.", "Quite a few people were born in the Year of the Goat.")),
        ("猴", "hóu", "Monkey (zodiac)", ("属猴的人很机灵。", "Shǔ hóu de rén hěn jīling.", "People born in the Year of the Monkey are quick-witted."), ("猴年大家想要聪明的孩子。", "Hóu nián dàjiā xiǎng yào cōngming de háizi.", "In Monkey years people want clever children.")),
        ("猪", "zhū", "Pig (zodiac)", ("属猪的人福气好。", "Shǔ zhū de rén fúqi hǎo.", "People born in the Year of the Pig are fortunate."), ("猪是最后一个生肖。", "Zhū shì zuìhòu yī gè shēngxiào.", "The Pig is the last zodiac sign.")),
    ],
    "arts": [
        ("书法", "shūfǎ", "calligraphy", ("书法是中国传统艺术。", "Shūfǎ shì Zhōngguó chuántǒng yìshù.", "Calligraphy is a traditional Chinese art."), ("他练习书法十年了。", "Tā liànxí shūfǎ shí nián le.", "He's practiced calligraphy for ten years.")),
        ("国画", "guóhuà", "Chinese painting", ("这幅国画是山水画。", "Zhè fú guóhuà shì shānshuǐ huà.", "This Chinese painting is a landscape."), ("国画用毛笔和墨水。", "Guóhuà yòng máobǐ hé mòshuǐ.", "Chinese painting uses brush and ink.")),
        ("京剧", "jīngjù", "Peking opera", ("京剧脸谱很有特色。", "Jīngjù liǎnpǔ hěn yǒu tèsè.", "Peking opera face paint is distinctive."), ("我们去听京剧。", "Wǒmen qù tīng jīngjù.", "We went to hear Peking opera.")),
        ("剪纸", "jiǎnzhǐ", "paper cutting", ("窗上贴了红色剪纸。", "Chuāng shàng tiē le hóngsè jiǎnzhǐ.", "Red paper cuttings are pasted on the window."), ("剪纸是民间艺术。", "Jiǎnzhǐ shì mínjiān yìshù.", "Paper cutting is folk art.")),
        ("刺绣", "cìxiù", "embroidery", ("苏绣非常有名。", "Sūxiù fēicháng yǒumíng.", "Su embroidery is very famous."), ("这件刺绣很精细。", "Zhè jiàn cìxiù hěn jīngxì.", "This embroidery is very fine.")),
        ("陶瓷", "táocí", "ceramics / porcelain", ("景德镇陶瓷闻名世界。", "Jǐngdézhèn táocí wénmíng shìjiè.", "Jingdezhen porcelain is world famous."), ("这个陶瓷花瓶很精美。", "Zhège táocí huāpíng hěn jīngměi.", "This ceramic vase is exquisite.")),
        ("二胡", "èrhú", "erhu (two-string fiddle)", ("她用二胡演奏。", "Tā yòng èrhú yǎnzòu.", "She performs on the erhu."), ("二胡声音很动人。", "Èrhú shēngyīn hěn dòngrén.", "The erhu sound is moving.")),
        ("古筝", "gǔzhēng", "guzheng (zither)", ("她从小学习古筝。", "Tā cóngxiǎo xuéxí gǔzhēng.", "She's studied guzheng since childhood."), ("古筝曲很优美。", "Gǔzhēng qǔ hěn yōuměi.", "Guzheng music is graceful.")),
        ("相声", "xiàngsheng", "cross-talk comedy", ("相声让人哈哈大笑。", "Xiàngsheng ràng rén dà xiào.", "Cross-talk makes people laugh hard."), ("我们在茶馆听相声。", "Wǒmen zài cháguǎn tīng xiàngsheng.", "We heard cross-talk at a teahouse.")),
        ("武术", "wǔshù", "martial arts", ("武术是中国传统体育。", "Wǔshù shì Zhōngguó chuántǒng tǐyù.", "Martial arts are traditional Chinese sport."), ("他从小练武术。", "Tā cóngxiǎo liàn wǔshù.", "He's practiced martial arts since childhood.")),
    ],
    "kungfu": [
        ("功夫", "gōngfu", "kung fu / martial skill", ("中国功夫闻名世界。", "Zhōngguó gōngfu wénmíng shìjiè.", "Chinese kung fu is world famous."), ("他练了十年功夫。", "Tā liàn le shí nián gōngfu.", "He's trained kung fu for ten years.")),
        ("太极拳", "tàijíquán", "Tai Chi", ("太极拳动作很慢。", "Tàijíquán dòngzuò hěn màn.", "Tai Chi movements are slow."), ("老人常在公园打太极拳。", "Lǎorén cháng zài gōngyuán dǎ tàijíquán.", "Elders often practice Tai Chi in parks.")),
        ("咏春", "Yǒngchūn", "Wing Chun", ("咏春拳来自广东。", "Yǒngchūn quán láizì Guǎngdōng.", "Wing Chun comes from Guangdong."), ("咏春讲究近身格斗。", "Yǒngchūn jiǎngjiū jìn shēn gédòu.", "Wing Chun focuses on close combat.")),
        ("少林寺", "Shàolín Sì", "Shaolin Temple", ("少林寺是功夫发源地。", "Shàolín Sì shì gōngfu fāyuándì.", "Shaolin Temple is the birthplace of kung fu."), ("我们去少林寺参观。", "Wǒmen qù Shàolín Sì cānguān.", "We visited Shaolin Temple.")),
        ("师傅", "shīfu", "master / teacher (martial)", ("师傅教了我很多。", "Shīfu jiāo le wǒ hěn duō.", "My master taught me a lot."), ("请师傅示范一下。", "Qǐng shīfu shìfàn yīxià.", "Master, please demonstrate.")),
        ("弟子", "dìzi", "disciple / student", ("他是少林寺的弟子。", "Tā shì Shàolín Sì de dìzi.", "He is a Shaolin disciple."), ("弟子要认真练功。", "Dìzi yào rènzhēn liàngōng.", "Disciples must train diligently.")),
        ("练功", "liàngōng", "to practice martial arts", ("每天练功两小时。", "Měitiān liàngōng liǎng xiǎoshí.", "Practice two hours daily."), ("练功要持之以恒。", "Liàngōng yào chízhī yǐhéng.", "Training requires persistence.")),
        ("套路", "tàolù", "form / routine (martial)", ("这套套路很难。", "Zhè tào tàolù hěn nán.", "This form is difficult."), ("他表演了一套拳法套路。", "Tā biǎoyǎn le yī tào quánfǎ tàolù.", "He performed a fist form routine.")),
        ("内功", "nèigōng", "internal martial skill", ("内功需要长期修炼。", "Nèigōng xūyào chángqī xiūliàn.", "Internal skill requires long cultivation."), ("他内功深厚。", "Tā nèigōng shēnhòu.", "His internal skill is profound.")),
        ("比武", "bǐwǔ", "martial arts contest", ("他们在比武。", "Tāmen zài bǐwǔ.", "They're in a martial contest."), ("比武点到为止。", "Bǐwǔ diǎn dào wéi zhǐ.", "In contests, stop at the point of contact.")),
    ],
}

TECHNOLOGY = {
    "smartphones": [
        ("智能手机", "zhìnéng shǒujī", "smartphone", ("智能手机改变了生活。", "Zhìnéng shǒujī gǎibiàn le shēnghuó.", "Smartphones changed our lives."), ("我换了新智能手机。", "Wǒ huàn le xīn zhìnéng shǒujī.", "I got a new smartphone.")),
        ("屏幕", "píngmù", "screen", ("这个屏幕很大。", "Zhège píngmù hěn dà.", "This screen is very large."), ("屏幕碎了要换。", "Píngmù suì le yào huàn.", "The cracked screen needs replacing.")),
        ("充电", "chōngdiàn", "to charge", ("手机快没电了，要充电。", "Shǒujī kuài méi diàn le, yào chōngdiàn.", "The phone is low, needs charging."), ("充电器在桌上。", "Chōngdiànqì zài zhuō shàng.", "The charger is on the table.")),
        ("应用", "yìngyòng", "app / application", ("你下载这个应用了吗？", "Nǐ xiàzài zhège yìngyòng le ma?", "Did you download this app?"), ("这个应用很好用。", "Zhège yìngyòng hěn hǎo yòng.", "This app is very useful.")),
        ("更新", "gēngxīn", "to update", ("请更新系统。", "Qǐng gēngxīn xìtǒng.", "Please update the system."), ("应用有新版本更新。", "Yìngyòng yǒu xīn bǎnběn gēngxīn.", "The app has a new update.")),
        ("指纹", "zhǐwén", "fingerprint", ("用指纹解锁手机。", "Yòng zhǐwén jiěsuǒ shǒujī.", "Unlock the phone with fingerprint."), ("指纹识别很快。", "Zhǐwén shíbié hěn kuài.", "Fingerprint recognition is fast.")),
        ("拍照", "pāizhào", "to take photos", ("手机拍照很方便。", "Shǒujī pāizhào hěn fāngbiàn.", "Phone photography is convenient."), ("请帮我拍张照。", "Qǐng bāng wǒ pāi zhāng zhào.", "Please take a photo for me.")),
        ("内存", "nèicún", "storage / memory", ("手机内存不够了。", "Shǒujī nèicún bú gòu le.", "Phone storage is full."), ("这个型号内存很大。", "Zhège xínghào nèicún hěn dà.", "This model has large storage.")),
        ("信号", "xìnhào", "signal", ("这里手机信号不好。", "Zhèlǐ shǒujī xìnhào bù hǎo.", "Cell signal is poor here."), ("信号满格了。", "Xìnhào mǎn gé le.", "Signal is at full bars.")),
        ("蓝牙", "lányá", "Bluetooth", ("请打开蓝牙。", "Qǐng dǎkāi lányá.", "Please turn on Bluetooth."), ("耳机通过蓝牙连接。", "Ěrjī tōngguò lányá liánjiē.", "Headphones connect via Bluetooth.")),
    ],
    "computers": [
        ("电脑", "diànnǎo", "computer", ("我的电脑运行很慢。", "Wǒ de diànnǎo yùnxíng hěn màn.", "My computer runs slowly."), ("请重启电脑试试。", "Qǐng chóngqǐ diànnǎo shìshi.", "Try restarting the computer.")),
        ("笔记本", "bǐjìběn", "laptop", ("我上班带笔记本。", "Wǒ shàngbān dài bǐjìběn.", "I bring my laptop to work."), ("这台笔记本很轻。", "Zhè tái bǐjìběn hěn qīng.", "This laptop is very light.")),
        ("键盘", "jiànpán", "keyboard", ("键盘有一个键坏了。", "Jiànpán yǒu yī gè jiàn huài le.", "One key on the keyboard is broken."), ("请连接无线键盘。", "Qǐng liánjiē wúxiàn jiànpán.", "Please connect the wireless keyboard.")),
        ("鼠标", "shǔbiāo", "mouse", ("鼠标不灵敏了。", "Shǔbiāo bù língmǐn le.", "The mouse isn't responsive."), ("我习惯用无线鼠标。", "Wǒ xíguàn yòng wúxiàn shǔbiāo.", "I prefer a wireless mouse.")),
        ("软件", "ruǎnjiàn", "software", ("请安装这个软件。", "Qǐng ānzhuāng zhège ruǎnjiàn.", "Please install this software."), ("软件崩溃了。", "Ruǎnjiàn bēngkuì le.", "The software crashed.")),
        ("硬盘", "yìngpán", "hard drive", ("硬盘空间不足。", "Yìngpán kōngjiān bùzú.", "Hard drive space is insufficient."), ("我换了一个固态硬盘。", "Wǒ huàn le yī gè gùtài yìngpán.", "I replaced it with a solid-state drive.")),
        ("备份", "bèifèn", "to back up", ("请定期备份数据。", "Qǐng dìngqī bèifèn shùjù.", "Please back up data regularly."), ("我已经备份到云端了。", "Wǒ yǐjīng bèifèn dào yúnduān le.", "I've backed up to the cloud.")),
        ("重启", "chóngqǐ", "to restart", ("重启电脑试试。", "Chóngqǐ diànnǎo shìshi.", "Try restarting the computer."), ("更新后需要重启。", "Gēngxīn hòu xūyào chóngqǐ.", "A restart is required after updating.")),
        ("显示器", "xiǎnshìqì", "monitor", ("我买了两个显示器。", "Wǒ mǎi le liǎng gè xiǎnshìqì.", "I bought two monitors."), ("显示器分辨率很高。", "Xiǎnshìqì fēnbiànlǜ hěn gāo.", "The monitor has high resolution.")),
        ("文件", "wénjiàn", "file", ("文件保存在桌面。", "Wénjiàn bǎocún zài zhuōmiàn.", "The file is saved on the desktop."), ("请把这个文件发给我。", "Qǐng bǎ zhège wénjiàn fā gěi wǒ.", "Please send me this file.")),
    ],
    "internet": [
        ("互联网", "hùliánwǎng", "internet", ("互联网改变了世界。", "Hùliánwǎng gǎibiàn le shìjiè.", "The internet changed the world."), ("没有互联网我无法工作。", "Méiyǒu hùliánwǎng wǒ wúfǎ gōngzuò.", "I can't work without the internet.")),
        ("网站", "wǎngzhàn", "website", ("请访问我们的网站。", "Qǐng fǎngwèn wǒmen de wǎngzhàn.", "Please visit our website."), ("这个网站加载很慢。", "Zhège wǎngzhàn jiāzài hěn màn.", "This website loads slowly.")),
        ("浏览器", "liúlǎnqì", "browser", ("请换一个浏览器试试。", "Qǐng huàn yī gè liúlǎnqì shìshi.", "Try a different browser."), ("浏览器需要更新。", "Liúlǎnqì xūyào gēngxīn.", "The browser needs updating.")),
        ("下载", "xiàzài", "to download", ("请下载最新版本。", "Qǐng xiàzài zuìxīn bǎnběn.", "Please download the latest version."), ("文件正在下载。", "Wénjiàn zhèngzài xiàzài.", "The file is downloading.")),
        ("上传", "shàngchuán", "to upload", ("请上传你的简历。", "Qǐng shàngchuán nǐ de jiǎnlì.", "Please upload your resume."), ("视频上传完成了。", "Shìpín shàngchuán wánchéng le.", "Video upload is complete.")),
        ("搜索", "sōusuǒ", "to search", ("请在网上搜索一下。", "Qǐng zài wǎngshàng sōusuǒ yīxià.", "Please search online."), ("搜索引擎很快。", "Sōusuǒ yǐnqíng hěn kuài.", "The search engine is fast.")),
        ("链接", "liànjiē", "link", ("请点击这个链接。", "Qǐng diǎnjī zhège liànjiē.", "Please click this link."), ("链接已经失效了。", "Liànjiē yǐjīng shīxiào le.", "The link has expired.")),
        ("密码", "mìmǎ", "password", ("请设置强密码。", "Qǐng shèzhì qiáng mìmǎ.", "Please set a strong password."), ("我忘了密码。", "Wǒ wàng le mìmǎ.", "I forgot my password.")),
        ("WiFi", "WiFi", "WiFi", ("WiFi密码是什么？", "WiFi mìmǎ shì shénme?", "What's the WiFi password?"), ("这里WiFi信号很强。", "Zhèlǐ WiFi xìnhào hěn qiáng.", "WiFi signal is strong here.")),
        ("云端", "yúnduān", "cloud", ("数据保存在云端。", "Shùjù bǎocún zài yúnduān.", "Data is stored in the cloud."), ("云端同步完成了。", "Yúnduān tóngbù wánchéng le.", "Cloud sync is complete.")),
    ],
    "ai": [
        ("人工智能", "réngōng zhìnéng", "artificial intelligence", ("人工智能发展很快。", "Rén gōng zhìnéng fāzhǎn hěn kuài.", "AI is developing rapidly."), ("人工智能改变了很多行业。", "Rén gōng zhìnéng gǎibiàn le hěn duō hángyè.", "AI has transformed many industries.")),
        ("算法", "suànfǎ", "algorithm", ("推荐算法很精准。", "Tuījiàn suànfǎ hěn jīngzhǔn.", "The recommendation algorithm is accurate."), ("算法需要不断优化。", "Suànfǎ xūyào bùduàn yōuhuà.", "Algorithms need constant optimization.")),
        ("模型", "móxíng", "model (AI)", ("这个语言模型很强大。", "Zhège yǔyán móxíng hěn qiángdà.", "This language model is powerful."), ("模型需要大量数据训练。", "Móxíng xūyào dàliàng shùjù xùnliàn.", "Models need large datasets to train.")),
        ("训练", "xùnliàn", "to train (AI)", ("模型训练需要很多时间。", "Móxíng xùnliàn xūyào hěn duō shíjiān.", "Model training takes a lot of time."), ("他们在训练新的AI。", "Tāmen zài xùnliàn xīn de AI.", "They're training a new AI.")),
        ("识别", "shíbié", "recognition / to recognize", ("人脸识别很快。", "Rénliǎn shíbié hěn kuài.", "Face recognition is fast."), ("语音识别准确率很高。", "Yǔyīn shíbié zhǔnquèlǜ hěn gāo.", "Speech recognition accuracy is high.")),
        ("自动化", "zìdònghuà", "automation", ("工厂实现了自动化。", "Gōngchǎng shíxiàn le zìdònghuà.", "The factory achieved automation."), ("自动化提高了效率。", "Zìdònghuà tígāo le xiàolǜ.", "Automation improved efficiency.")),
        ("智能", "zhìnéng", "smart / intelligent", ("这是智能家居系统。", "Zhè shì zhìnéng jiājū xìtǒng.", "This is a smart home system."), ("智能助手可以回答问题。", "Zhìnéng zhùshǒu kěyǐ huídá wèntí.", "Smart assistants can answer questions.")),
        ("数据", "shùjù", "data", ("数据安全很重要。", "Shùjù ānquán hěn zhòngyào.", "Data security is important."), ("请分析这些数据。", "Qǐng fēnxī zhèxiē shùjù.", "Please analyze this data.")),
        ("机器学习", "jīqì xuéxí", "machine learning", ("机器学习是AI的基础。", "Jīqì xuéxí shì AI de jīchǔ.", "Machine learning is the foundation of AI."), ("他在学机器学习。", "Tā zài xué jīqì xuéxí.", "He's studying machine learning.")),
        ("聊天机器人", "liáotiān jīqìrén", "chatbot", ("客服是聊天机器人。", "Kèfú shì liáotiān jīqìrén.", "Customer service is a chatbot."), ("聊天机器人回答很快。", "Liáotiān jīqìrén huídá hěn kuài.", "The chatbot responds quickly.")),
    ],
    "social_media": [
        ("朋友圈", "péngyou quān", "Moments (WeChat feed)", ("他在朋友圈发了照片。", "Tā zài péngyou quān fā le zhàopiàn.", "He posted photos on Moments."), ("别什么都发在朋友圈。", "Bié shénme dōu fā zài péngyou quān.", "Don't post everything on Moments.")),
        ("点赞", "diǎnzàn", "to like (a post)", ("请给我的视频点赞。", "Qǐng gěi wǒ de shìpín diǎnzàn.", "Please like my video."), ("这条帖子点赞很多。", "Zhè tiáo tiězi diǎnzàn hěn duō.", "This post got many likes.")),
        ("评论", "pínglùn", "comment", ("请留下你的评论。", "Qǐng liúxià nǐ de pínglùn.", "Please leave your comment."), ("评论里讨论很热烈。", "Pínglùn lǐ tǎolùn hěn rèliè.", "Discussion in the comments is lively.")),
        ("分享", "fēnxiǎng", "to share", ("请分享这篇文章。", "Qǐng fēnxiǎng zhè piān wénzhāng.", "Please share this article."), ("我分享到微信了。", "Wǒ fēnxiǎng dào Wēixìn le.", "I shared it on WeChat.")),
        ("关注", "guānzhù", "to follow", ("请关注我的账号。", "Qǐng guānzhù wǒ de zhànghào.", "Please follow my account."), ("他关注了很多博主。", "Tā guānzhù le hěn duō bózhǔ.", "He follows many influencers.")),
        ("粉丝", "fěnsī", "fans / followers", ("他有一百万粉丝。", "Tā yǒu yī bǎi wàn fěnsī.", "He has a million followers."), ("粉丝们很热情。", "Fěnsīmen hěn rèqíng.", "The fans are enthusiastic.")),
        ("直播", "zhíbō", "live stream", ("她今晚有直播。", "Tā jīn wǎn yǒu zhíbō.", "She has a live stream tonight."), ("直播带货很流行。", "Zhíbō dài huò hěn liúxíng.", "Live-stream selling is very popular.")),
        ("短视频", "duǎn shìpín", "short video", ("短视频很容易上瘾。", "Duǎn shìpín hěn róngyì shàngyǐn.", "Short videos are easily addictive."), ("他拍了很多短视频。", "Tā pāi le hěn duō duǎn shìpín.", "He made many short videos.")),
        ("热搜", "rèsōu", "trending search", ("这条新闻上了热搜。", "Zhè tiáo xīnwén shàng le rèsōu.", "This news hit trending searches."), ("热搜第一名是这个话题。", "Rèsōu dì yī míng shì zhège huàtí.", "This topic is number one trending.")),
        ("私信", "sīxìn", "private message", ("请私信联系我。", "Qǐng sīxìn liánxi wǒ.", "Please contact me via DM."), ("我收到了一条私信。", "Wǒ shōudào le yī tiáo sīxìn.", "I received a private message.")),
    ],
    "online_shopping": [
        ("网购", "wǎnggòu", "online shopping", ("我习惯网购。", "Wǒ xíguàn wǎnggòu.", "I'm used to shopping online."), ("网购很方便。", "Wǎnggòu hěn fāngbiàn.", "Online shopping is convenient.")),
        ("购物车", "gòuwùchē", "shopping cart", ("请加入购物车。", "Qǐng jiārù gòuwùchē.", "Please add to cart."), ("我的购物车满了。", "Wǒ de gòuwùchē mǎn le.", "My cart is full.")),
        ("下单", "xiàdān", "to place an order", ("我已经下单了。", "Wǒ yǐjīng xiàdān le.", "I've already placed the order."), ("请在今晚前下单。", "Qǐng zài jīn wǎn qián xiàdān.", "Please order before tonight.")),
        ("快递", "kuàidì", "express delivery", ("快递明天到。", "Kuàidì míngtiān dào.", "Express delivery arrives tomorrow."), ("请查一下快递到哪了。", "Qǐng chá yīxià kuàidì dào nǎ le.", "Please check where the package is.")),
        ("评价", "píngjià", "review / rating", ("请给商品评价。", "Qǐng gěi shāngpǐn píngjià.", "Please review the product."), ("这个评价很有帮助。", "Zhège píngjià hěn yǒu bāngzhù.", "This review is very helpful.")),
        ("退款", "tuìkuǎn", "refund", ("我可以申请退款吗？", "Wǒ kěyǐ shēnqǐng tuìkuǎn ma?", "Can I request a refund?"), ("退款已经到账了。", "Tuìkuǎn yǐjīng dào zhàng le.", "The refund has been credited.")),
        ("优惠券", "yōuhuìquàn", "coupon", ("我有优惠券。", "Wǒ yǒu yōuhuìquàn.", "I have a coupon."), ("优惠券今天到期。", "Yōuhuìquàn jīntiān dàoqī.", "The coupon expires today.")),
        ("秒杀", "miǎoshā", "flash sale", ("今晚八点有秒杀。", "Jīn wǎn bā diǎn yǒu miǎoshā.", "There's a flash sale at 8 tonight."), ("秒杀价格很优惠。", "Miǎoshā jiàgé hěn yōuhuì.", "Flash sale prices are great deals.")),
        ("包邮", "bāoyóu", "free shipping", ("满一百包邮。", "Mǎn yībǎi bāoyóu.", "Free shipping on orders over 100."), ("这个商品包邮。", "Zhège shāngpǐn bāoyóu.", "This item ships free.")),
        ("客服", "kèfú", "customer service", ("请联系在线客服。", "Qǐng liánxi zàixiàn kèfú.", "Please contact online customer service."), ("客服回复很快。", "Kèfú huífù hěn kuài.", "Customer service replied quickly.")),
    ],
    "delivery": [
        ("外卖", "wàimài", "food delivery", ("今晚叫外卖吧。", "Jīn wǎn jiào wàimài ba.", "Let's order delivery tonight."), ("外卖三十分钟到。", "Wàimài sānshí fēnzhōng dào.", "Delivery arrives in thirty minutes.")),
        ("骑手", "qíshǒu", "delivery rider", ("骑手已经在路上了。", "Qíshǒu yǐjīng zài lù shàng le.", "The rider is already on the way."), ("骑手打电话说到了。", "Qíshǒu dǎ diànhuà shuō dào le.", "The rider called to say they've arrived.")),
        ("配送", "pèisòng", "delivery / distribution", ("配送费五块钱。", "Pèisòng fèi wǔ kuài qián.", "Delivery fee is five yuan."), ("预计配送时间四十分钟。", "Yùjì pèisòng shíjiān sìshí fēnzhōng.", "Estimated delivery time is forty minutes.")),
        ("订单", "dìngdān", "order", ("你的订单已发出。", "Nǐ de dìngdān yǐ fāchū.", "Your order has been dispatched."), ("请确认订单信息。", "Qǐng quèrèn dìngdān xìnxī.", "Please confirm order details.")),
        ("追踪", "zhuīzōng", "to track", ("可以实时追踪配送。", "Kěyǐ shíshí zhuīzōng pèisòng.", "You can track delivery in real time."), ("请追踪我的包裹。", "Qǐng zhuīzōng wǒ de bāoguǒ.", "Please track my package.")),
        ("准时", "zhǔnshí", "on time", ("外卖准时送到了。", "Wàimài zhǔnshí sòng dào le.", "Delivery arrived on time."), ("请尽量准时送达。", "Qǐng jǐnliàng zhǔnshí sòngdá.", "Please deliver on time if possible.")),
        ("保温", "bǎowēn", "keep warm (packaging)", ("外卖用了保温袋。", "Wàimài yòng le bǎowēn dài.", "Delivery used an insulated bag."), ("保温效果还不错。", "Bǎowēn xiàoguǒ hái búcuò.", "Insulation works reasonably well.")),
        ("评价", "píngjià", "to rate (delivery)", ("请给骑手评价。", "Qǐng gěi qíshǒu píngjià.", "Please rate the rider."), ("我给了一个好评。", "Wǒ gěi le yī gè hǎopíng.", "I gave a positive rating.")),
        ("小费", "xiǎofèi", "tip", ("你想给骑手小费吗？", "Nǐ xiǎng gěi qíshǒu xiǎofèi ma?", "Would you like to tip the rider?"), ("我给了十块小费。", "Wǒ gěi le shí kuài xiǎofèi.", "I gave a ten yuan tip.")),
        ("取餐码", "qǔ cān mǎ", "pickup code", ("请出示取餐码。", "Qǐng chūshì qǔ cān mǎ.", "Please show your pickup code."), ("取餐码发到你手机了。", "Qǔ cān mǎ fā dào nǐ shǒujī le.", "The pickup code was sent to your phone.")),
    ],
    "gaming": [
        ("游戏", "yóuxì", "game", ("你玩什么游戏？", "Nǐ wán shénme yóuxì?", "What games do you play?"), ("这个游戏很好玩。", "Zhège yóuxì hěn hǎowán.", "This game is fun.")),
        ("玩家", "wánjiā", "player / gamer", ("他是资深玩家。", "Tā shì zīshēn wánjiā.", "He's a veteran gamer."), ("在线玩家很多。", "Zàixiàn wánjiā hěn duō.", "There are many players online.")),
        ("手柄", "shǒubǐng", "game controller", ("请连接手柄。", "Qǐng liánjiē shǒubǐng.", "Please connect the controller."), ("这个手柄手感很好。", "Zhège shǒubǐng shǒugǎn hěn hǎo.", "This controller feels great.")),
        ("关卡", "guānkǎ", "level / stage", ("这个关卡很难。", "Zhège guānkǎ hěn nán.", "This level is hard."), ("我过了第三关。", "Wǒ guò le dì sān guān.", "I cleared level three.")),
        ("排名", "páimíng", "ranking", ("我的排名上升了。", "Wǒ de páimíng shàngshēng le.", "My ranking went up."), ("他在全球排名第一。", "Tā zài quánqiú páimíng dì yī.", "He's ranked number one globally.")),
        ("组队", "zǔduì", "to team up", ("我们组队打游戏吧。", "Wǒmen zǔduì dǎ yóuxì ba.", "Let's team up to play."), ("组队需要四个人。", "Zǔduì xūyào sì gè rén.", "Teaming up requires four people.")),
        ("充值", "chōngzhí", "to top up / recharge", ("游戏需要充值吗？", "Yóuxì xūyào chōngzhí ma?", "Does the game require top-ups?"), ("我充值了六十八块。", "Wǒ chōngzhí le liùshíbā kuài.", "I topped up sixty-eight yuan.")),
        ("装备", "zhuāngbèi", "equipment / gear (gaming)", ("这个装备属性很好。", "Zhège zhuāngbèi shǔxìng hěn hǎo.", "This gear has great stats."), ("请升级你的装备。", "Qǐng shēngjí nǐ de zhuāngbèi.", "Please upgrade your gear.")),
        ("网速", "wǎngsù", "internet speed", ("网速太慢影响游戏。", "Wǎngsù tài màn yǐngxiǎng yóuxì.", "Slow internet affects gaming."), ("换宽带后网速快了。", "Huàn kuǎndài hòu wǎngsù kuài le.", "Internet speed improved after switching broadband.")),
        ("电竞", "diànjìng", "esports", ("电竞现在是正规比赛。", "Diànjìng xiànzài shì zhèngguī bǐsài.", "Esports is now an official competitive sport."), ("他梦想成为电竞选手。", "Tā mèngxiǎng chéngwéi diànjìng xuǎnshǒu.", "He dreams of becoming a pro gamer.")),
    ],
    "smart_devices": [
        ("智能音箱", "zhìnéng yīnxiāng", "smart speaker", ("智能音箱可以控制家电。", "Zhìnéng yīnxiāng kěyǐ kòngzhì jiādiàn.", "Smart speakers can control home appliances."), ("请对着智能音箱说话。", "Qǐng duì zhe zhìnéng yīnxiāng shuōhuà.", "Speak to the smart speaker.")),
        ("智能手表", "zhìnéng shǒubiǎo", "smartwatch", ("智能手表可以测心率。", "Zhìnéng shǒubiǎo kěyǐ cè xīnlǜ.", "Smartwatches can measure heart rate."), ("我戴智能手表跑步。", "Wǒ dài zhìnéng shǒubiǎo pǎobù.", "I wear a smartwatch when running.")),
        ("智能家居", "zhìnéng jiājū", "smart home", ("智能家居让生活更方便。", "Zhìnéng jiājū ràng shēnghuó gèng fāngbiàn.", "Smart homes make life easier."), ("我们装了智能家居系统。", "Wǒmen zhuāng le zhìnéng jiājū xìtǒng.", "We installed a smart home system.")),
        ("语音助手", "yǔyīn zhùshǒu", "voice assistant", ("语音助手可以设闹钟。", "Yǔyīn zhùshǒu kěyǐ shè nàozhōng.", "Voice assistants can set alarms."), ("请叫语音助手播放音乐。", "Qǐng jiào yǔyīn zhùshǒu bōfàng yīnyuè.", "Ask the voice assistant to play music.")),
        ("扫地机器人", "sǎodì jīqìrén", "robot vacuum", ("扫地机器人每天自动打扫。", "Sǎodì jīqìrén měitiān zìdòng dǎsǎo.", "The robot vacuum cleans automatically daily."), ("请清空扫地机器人的尘盒。", "Qǐng qīngkōng sǎodì jīqìrén de chénhé.", "Please empty the robot vacuum's dust bin.")),
        ("智能门锁", "zhìnéng ménsuǒ", "smart lock", ("智能门锁用密码开。", "Zhìnéng ménsuǒ yòng mìmǎ kāi.", "The smart lock opens with a code."), ("我设置了智能门锁。", "Wǒ shèzhì le zhìnéng ménsuǒ.", "I set up a smart lock.")),
        ("监控", "jiānkòng", "surveillance / monitor", ("门口装了监控摄像头。", "Ménkǒu zhuāng le jiānkòng shèxiàngtóu.", "A security camera is installed at the door."), ("可以通过手机看监控。", "Kěyǐ tōngguò shǒujī kàn jiānkòng.", "You can view surveillance on your phone.")),
        ("传感器", "chuángǎnqì", "sensor", ("传感器检测到有人。", "Chuángǎnqì jiǯcè dào yǒu rén.", "The sensor detected someone."), ("温度传感器很准确。", "Wēndù chuángǎnqì hěn zhǔnquè.", "The temperature sensor is accurate.")),
        ("远程控制", "yuǎnchéng kòngzhì", "remote control", ("可以远程控制空调。", "Kěyǐ yuǎnchéng kòngzhì kōngtiáo.", "You can control the AC remotely."), ("远程控制很方便。", "Yuǎnchéng kòngzhì hěn fāngbiàn.", "Remote control is convenient.")),
        ("连接", "liánjiē", "to connect", ("设备连接成功了。", "Shèbèi liánjiē chénggōng le.", "Device connected successfully."), ("请连接同一个WiFi。", "Qǐng liánjiē tóng yī gè WiFi.", "Please connect to the same WiFi.")),
    ],
    "electronics": [
        ("电池", "diànchí", "battery", ("电池快没电了。", "Diànchí kuài méi diàn le.", "The battery is almost dead."), ("请换新电池。", "Qǐng huàn xīn diànchí.", "Please replace the battery.")),
        ("充电线", "chōngdiàn xiàn", "charging cable", ("我的充电线坏了。", "Wǒ de chōngdiàn xiàn huài le.", "My charging cable is broken."), ("请借我一条充电线。", "Qǐng jiè wǒ yī tiáo chōngdiàn xiàn.", "Please lend me a charging cable.")),
        ("耳机", "ěrjī", "headphones / earphones", ("无线耳机很方便。", "Wúxiàn ěrjī hěn fāngbiàn.", "Wireless earphones are convenient."), ("耳机音质很好。", "Ěrjī yīnzhì hěn hǎo.", "The headphones have great sound quality.")),
        ("摄像头", "shèxiàngtóu", "camera (device)", ("笔记本电脑有摄像头。", "Bǐjìběn diànnǎo yǒu shèxiàngtóu.", "The laptop has a camera."), ("请打开摄像头。", "Qǐng dǎkāi shèxiàngtóu.", "Please turn on the camera.")),
        ("路由器", "lùyóuqì", "router", ("路由器在客厅。", "Lùyóuqì zài kètīng.", "The router is in the living room."), ("请重启路由器。", "Qǐng chóngqǐ lùyóuqì.", "Please restart the router.")),
        ("插座", "chāzuò", "power outlet / socket", ("插座在哪里？", "Chāzuò zài nǎlǐ?", "Where is the outlet?"), ("这个插座坏了。", "Zhège chāzuò huài le.", "This outlet is broken.")),
        ("电源", "diànyuán", "power supply", ("请检查电源连接。", "Qǐng jiǎnchá diànyuán liánjiē.", "Please check the power connection."), ("电源适配器不见了。", "Diànyuán shìpèiqì bú jiàn le.", "The power adapter is missing.")),
        ("屏幕", "píngmù", "screen / display", ("屏幕分辨率是4K。", "Píngmù fēnbiànlǜ shì 4K.", "The screen resolution is 4K."), ("屏幕上有划痕。", "Píngmù shàng yǒu huàhén.", "There are scratches on the screen.")),
        ("保修", "bǎoxiū", "warranty", ("这个产品保修一年。", "Zhège chǎnpǐn bǎoxiū yī nián.", "This product has a one-year warranty."), ("保修期过了。", "Bǎoxiūqī guò le.", "The warranty period has expired.")),
        ("维修", "wéixiū", "to repair / maintenance", ("手机需要维修。", "Shǒujī xūyào wéixiū.", "The phone needs repair."), ("维修店在商场里。", "Wéixiū diàn zài shāngchǎng lǐ.", "The repair shop is in the mall.")),
    ],
}
